ROCm/ROCm

README.md
- 1.4 needed to be removed with `sudo apt remove hsa-rocr-dev hsa-ext-rocr-dev rocm-smi hsakmt-roct-dev`
- The name of the opencl-rocm and opencl-rocm-dev changed to rocm-opencl and rocm-opencl-dev
=> Feedback from updating 1.4 to 1.5 on Ubuntu 16.04

README.md
Improved practice of running echo as user instead of sudo, then piping the output into a redirection that uses sudo in order to write into a file that requires sudo permissions.
=> Update README.md, delaying use of sudo until necessary

README.md, default.xml
Changes to ROCm README:
* Putting the current ROCm version right at the top to prevent confusion
* Adding a table of contents because this README is getting somewhat long.
* Updating the hardware support section to be more specific about what GPUs we support, in an attempt to match the [long-form hardware support list](https://rocm.github.io/hardware.html).
* Other minor changes:
* Re-align sections/subsections so that CentOS/RHEL directions are contained under "Installing from AMD ROCm repositories" instead of on the same level as that.
=> Updating README file to better describe hardware support

README.md
This PR specifies the ROCm recommended Ubuntu kernel versions.
And advise users to remove ROCm packages if need to upgrade the CentOS versions. There are known DKMS limitations can cause the system fail to upgrade if rock-dkms modules were installed.
=> Updated doc on OS support

README.md, default.xml, version_history.md
Community feedback has pointed out a number of confusing,
oudated, or missing sections in our ROCm README file. For example,
we do not describe what our ROCm package structure is, or how the
packages and meta-packages fit together. This can make it confusing
for users who do not want to just install rocm-dkms and move on.
Our repo manifest (default.xml) is severely out of date. It is
missing almost all of the current ROCm projects, and it always
pulls from the main development branch. This means we do not have
a pinned manifest that allows you to pull the code from a
particular ROCm reelease. Manifest updated, and the section of the
README discussing it is majorly overhauled (including links for
information/scripts about building the code after downloading it).
Rather than continually …
=> README and repo overhaul for the ROCm 2.0 release

default.xml
llvm and device-libs use wrong tag and cause build errors.
=> llvm and device-libs should use tag roc-ocl-2.7.0

default.xml
OpenCL-ICD-Loader commit hash for 2.9.0 release need to update for OpenCL.
=> Update OpenCL-ICD-Loader commit hash for 2.9.0

default.xml
There is hipFFT on <http://repo.radeon.com/rocm/apt/4.1/pool/main/h/hipfft/>.
Please add related repository in default.xml.
Thank you.
=> add hipFFT to default.xml

README.md
Fixed code formatting, broken URLs and changelog table. The easiest way to see the result of these changes is on my fork: https://github.com/cgmb/ROCm-1/blob/patch-1/README.md
The most obvious differences are found the section "ROCm Math and Communication Libraries"
Though, I also fixed some of the code formatting:
=> Cleanup README.md formatting

README.md
The document structure is blurred by all these release note sections.
Put them in a global release note section to make the documentation more readable.
There are still a lot of things that could be reorganized but start simple.
=> Add release note section

README.md
Wrong Ubuntu version was mentioned in the release notes.
=> Fixing Ubuntu 22 to Ubuntu 20

docs/conf.py
ROCm already links to main ROCm docs in default sidebar header unlike other subprojects
Build: https://readthedocs.com/projects/advanced-micro-devices-rocm/builds/1356063/
=> Hide link to main ROCm docs in ROCm repo

docs/quick_start.md
Reorganize the quick start guide for linux, adding multi level tab selection for just the commands where it makes sense.
Currently mostly Ubuntu commands are filled out, if the structure looks fine, then more will follow.
=> Update quick start guide for Ubuntu

.github/workflows/markdownlint.yml, .mdlrc, mdlrc-style.rb
Closes #1946
- This PR enables all the warnings the Ruby version of Markdownlint supports with mostly default values (except for line length, which is escaped by giving it an extreme value).
- All violating files have been exempted from checks.
- Expectation is that files are removed from exclusion one-by-one and errors are resolved either via fixing up the content _or_ the style file if it's decided that some Markdown recommendation doesn't apply to us or it's too much work for too little value.
=> Initial Markdown linting

docs/hip_sdk_install_win/hip_sdk_install_win.md, docs/reference/rocmcc/rocmcc.md
Resolves #1955
Scope
- Replaces table captions and headers with MyST-style captions.
- Replaces some tables with the `:::{option}`-directive.
- Uses MyST-style figures for the Windows SDK Installation guide.
- Uses numref whenever possible.
Note for reviewer: I did not touch the clang options table, apart from wrapping it into a table directive. Is this table auto-generated? If so, how? Then we can use the same `:::{option}` directives for the arguments ^^
I.e.
```
:::{option} -dsym-dir <dir>
**Unsupported!**
Outputs dSYMs (if any) to the specified directory.
:::
```
=> ROCmCC & Win Install: Table & Figures Cleanup

.github/workflows/linters.yml
Closes #1947
- This PR adds basic ReST linting. The module supports no configuration beyond setting a linting level. Default warning is used.
- One document doesn't pass information level diagnostics.
=> Initial ReST linting

docs/understand/file_reorg.md
As @saadrahim [noted](https://github.com/RadeonOpenCompute/ROCm/pull/1951#pullrequestreview-1343884222) , here is the PR addressing comments found in the original PR that went stale.
- Unify code block style (indent vs. fence)
- Mark code languages
- Increase heading level one at a time
- No extra newlines between paragraphs
- List for header reorg stages
- Shrink ascii table (mobile friendliness)
- 80-column width
=> Comment triage of #1951

.github/dependabot.yml
The manifests are in the docs/.sphinx directory.
=> ci(deps): Fix dependabot config

docs/reference/openmp/openmp.md
The flags used for the OpenMP example are quite outdated and simplified flags are available with LLVM compilers (clang). The location of OpenMP examples in the ROCm directory tree have also changed since this information was last updated. I also found some minor typos.
=> Updated outdated OpenMP information

.github/workflows/markdownlint.yml
Fixes checks not passing due to stricter markdown linting.
=> Ignore markdown linting in autotag template folder

.readthedocs.yaml
reason: increases rtd builds drastically and times out on correct links
=> Remove linkcheck step from rtd

CONTRIBUTING.md
rocm-docs-core dependencies requires python>=3.8 and python<3.9
=> Update supported python versions for documentation

docs/.sphinx/_toc.yml.in, docs/deploy/docker.md, docs/deploy/linux/quick_start.md, docs/index.md, docs/reference/gpu_isolation.md
- Adds back the GPU isolation page summarizing environment variables, docker, and GPU passthrough options
- Small touchup to the linux quick start guide adding a hover text to `DKMS`
=> Add GPU isolation

docs/understand/file_reorg.md
Fix a typo that would have missed the spellcheck.  Noticed this while reviewing the link that was shared with LLNL collaborators.
=> Minor update file_reorg.md

docs/conf.py, docs/deploy/linux/index.md, docs/how_to/system_debugging.md, docs/reference/ai_tools.md, docs/reference/all.md, docs/reference/compilers.md, docs/reference/computer_vision.md, docs/reference/gpu_libraries/c++_primitives.md, docs/reference/gpu_libraries/communication.md, docs/reference/gpu_libraries/fft.md, docs/reference/gpu_libraries/linear_algebra.md, docs/reference/gpu_libraries/math.md, docs/reference/gpu_libraries/rand.md, docs/reference/hip.md, docs/reference/management_tools.md, docs/reference/openmp/openmp.md, docs/reference/validation_tools.md, docs/sphinx/_toc.yml.in
Requires: https://github.com/RadeonOpenCompute/rocm-docs-core/pull/213
=> Replace links to subprojects docs with intersphinx links

docs/deploy/linux/installer/install.md, docs/deploy/linux/os-native/install.md
use the same versions in the install instructions for consistency
update version in instructions: rocm 5.4.3 > rocm 5.5.1
=> Standardize install instructions

docs/deploy/linux/prerequisites.md
Add instructions for adding extra repositories in RHEL and SLES
The hip-devel package depends on perl modules not distributed by default
on RHEL and SLES distriubutions, these can be installed from EPEL and
the `devel:languages:perl` repository respectively.
Ideally in the future these dependencies would be replaced with packages
available from default repositories, but in the meanwhile this should
be at least documented.
Based on #2228 to avoid conflicts, only the last commit is new in this PR
=> Install extra repos

CHANGELOG.md, RELEASE.md, tools/autotag/templates/rocm_changes/5.6.0.md
Adds the `hipStreamGetDevice` method from the HIP API to the 5.6.0 autotag template for inclusion in the 5.6.x changelog and release notes
Also updates the release notes and changelog with the tag script.
=> Update changelog and release notes with hipStreamGetDevice

docs/how_to/gpu_aware_mpi.md, docs/release/3rd_party_support_matrix.md
- simplify the configure arguments of UCX to only use flags absolutely required for ROCm
- add the UCC compatibility matrix to the docs
=> gpu-aware MPI udpates

.github/workflows/linting.yml
RE: https://github.com/RadeonOpenCompute/ROCm/actions/runs/5931515287?pr=2392
`Canceling since a deadlock for concurrency group 'refs/pull/2392/merge-Linting' was detected between 'top level workflow' and 'call-workflow-passing-data'`
https://docs.github.com/en/actions/using-jobs/using-concurrency
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
=> build: concurrency for linting to prevent deadlock

.github/workflows/linting.yml, docs/reference/openmp/openmp.md, docs/release/gpu_os_support.md
specify width and height for openmp toolchain svg to avoid RTD build failing on latexpdf
```
! LaTeX Error: Cannot determine size of graphic in openmp_toolchain.svg (no Bou
ndingBox).
pdflatex: Command for 'pdflatex' gave return code 36096
```
also reverts linting changes to avoid concurrency error
`Canceling since a deadlock for concurrency group 'refs/pull/2398/merge-Linting' was detected between 'top level workflow' and 'call-workflow-passing-data'`
=> fix RTD build failing on pdflatex and linting deadlock

docs/reference/all.md, docs/reference/gpu_libraries/c++_primitives.md
Needs this PR to go in https://github.com/RadeonOpenCompute/rocm-docs-core/pull/365
Then needs an update of rocm-docs-core in requirements.in/txt
=> Add hiptensor to list of ROCm libraries

docs/deploy/linux/installer/install.md
Fix RHEL9 instructions
Update 5.6.0 to 5.6.1 instructions
5.4.6 and 5.5.3 do not exist
=> Roc 5.6.x to docs/5.6.1

docs/about/compatibility/windows-support.md
Corrected the RX 6700 series LLVM target to "gfx1031" in windows_support.md
Changed name from "RX 6750" to "RX 6750 XT"
=> RX 6700* doc fixes in windows_support.md 

docs/tutorials/install/linux/os-native/install.md
Since we are not installing the ROCm OpenCL packages.  We are not able to test ROCm withg this command.
=> Removed reference /opt/rocm/opencl/bin/clinfo

docs/tutorials/install/linux/os-native/install.md
The export PATH rocm folder name does not reflect the folder name used in /opt/rocm-5.7.0.
=> Fixed invalid path.

tools/autotag/util/defaults.py
Since the repository name (AMDMIGraphX) and the indicated name of the changed library in the change log (MIGraphX) are not identical, AutoTag normally rejects the entry. This change removes that check since it's not really needed and resolves this issue.
CC: @samjwu
=> AutoTag: Fix MIGraphX change log not being parsed

.readthedocs.yaml
Because rubric is not supported
ValueError: <container: <rubric...><container...>> is not in list
=> Disable epub format in rtd yaml config

docs/deploy/linux/quick_start.md.jinja
Move instructions into text instead of tab
Install drivers
Install the amdgpu-dkms kernel module, aka driver, on your system.
=> Fix typo in Quick Start Jinja file

.github/dependabot.yml, docs/sphinx/requirements.in, docs/sphinx/requirements.txt
dependabot mis-detected the repository to be a library (instead of an application) and widened the rocm-docs-core verison instead of increasing it. This basically disabled pinning.
Explicitly specify to increase the version instead of widening it to hopefully prevent this in the future.
=> Bump rocm-docs-core version and fix dependabot settings

docs/release/gpu_os_support.md
Update docs with information in the [AMD blog post](https://community.amd.com/t5/ai/amd-extends-support-for-pytorch-machine-learning-development-on/ba-p/637756) announcing support for the Radeon™ RX 7900 XTX and the Radeon™ PRO W7900 on Linux.
The discrepancy between the blog post and docs is causing some confusion for those of us who have been asking for and keeping an eye on ROCm support for RDNA3 consumer GPUs on Linux. Speaking of which, there are already plenty of open issues and discussions on the topic, this will help give a more definitive answer to the inquirers.
- https://github.com/RadeonOpenCompute/ROCm/discussions/1891#discussioncomment-7300715_
- https://github.com/RadeonOpenCompute/ROCm/discussions/2559#discussioncomment-7303462_
- …
=> Update GPU Support on Linux for GPU name typo and issue close out

docs/deploy/linux/quick_start.md
The current instruction would mess apt update for rocm repo updates. just had a check, this error has been fixed from docs/5.5.1 onwards.
=> fix issue of ROCm docs/5.5.0  quick start  for ubuntu22.04

docs/conceptual/cmake-packages.rst
=> Clarify mixing C++ and HIP sources via CMake

docs/release/versions.md
This is used by the Version List header. Needed to prevent 404 from appearing in 6.0.0 docs
=> docs(versions.md): Add back docs versions page

CHANGELOG.md, RELEASE.md
There is no 22.04.5 exist.
It's 22.04.3 which has been tested and supported
=> Corrected OS version

CONTRIBUTING.md
Small text change to have PRs target default branch, not just develop branch.  To cover those repos that don't use develop.
=> Update Contributing.md to direct PRs to use repo's default branch

.github/workflows/issue_retrieval.yml
Spoke with GitHub admin team as to why my GitHub action was still not running. They told me that the repo variables/secrets were not set and that I needed to that first. They granted me admin privileges for ROCm and I've added the necessary secrets to get the action to work. I modified the workflow file to point to it.
=> Added repository secrets to ROCm and pointing the workflow file to use them

README.md
Fix broken link to building.md in the README.  It was missing `/docs/` in the path.
=> Fix link to building.md in README

docs/sphinx/requirements.in, docs/sphinx/requirements.txt
rocm-docs-core v0.37.1 should have the 6.0.2 header and no banner
=> Update doc requirements to 6.0.2 point fix

tools/autotag/README.md
IMPORTANT: It is key to update the template Markdown files in `tools/autotag/templates/rocm_changes` (eg: `5.6.0.md`) and not the `CHANGELOG.md` itself to ensure that updates are not overwritten by the script
=> Add best practice for updating changelog

docs/what-is-rocm.rst
This PR:
- Adds [rocDecode](https://rocm.docs.amd.com/projects/rocDecode/en/latest/) to the *What is ROCm?* page.
- Fixes typos in the *What is ROCm?* page.
=> Add rocDecode to What is ROCm? components list

docs/reference/api-libraries.md
This PR adds a link to rocDecode in the API libraries table.
=> Add rocDecode to API libraries

default.xml, docs/release/versions.md
Followup to https://github.com/ROCm/ROCm/pull/3025
=> Merge roc-6.1.x into docs/6.1.0

tools/autotag/README.md
IMPORTANT: It is key to update the template Markdown files in `tools/autotag/templates/rocm_changes` (eg: `5.6.0.md`) and not the `CHANGELOG.md` itself to ensure that updates are not overwritten by the autotag script. The template should only have content from changelogs that are not included by the script to avoid duplicating data.
Refer to existing templates for examples (eg: 6.0.0.md)
=> Add additional autotag script note to avoid duplicating data in changelog template

docs/index.md
This PR adds a link to the JAX installation guide under `Install`.
=> Add 'JAX for ROCm' link to index.md

docs/reference/api-libraries.md, docs/what-is-rocm.rst
This PR
- Updates the link to rocAL on the `What is ROCm?` page
- Add a link to rocAL in API libraries
=> Update links to rocAL component

docs/about/compatibility/precision-support.rst
This PR updates the links in `compatibility/precision-support` to relative links pointing to `latest` component docs. Undoes changes to links in #2992.
=> Update compatibility/precision-support links

docs/reference/gpu-arch-specs.rst
This PR fixes a broken link on the hardware specs page to the HIP programming model reference due to refactoring of HIP docs.
=> Fix broken link on hardware specs page

docs/reference/gpu-arch-specs.rst
* Fix broken link
Fix broken link on hardware specs page to HIP programming model due to refactoring of HIP docs.
* Update link anchor
=> Add 'Fix broken link on hardware specs page (#3075)' to 6.1.0

.azuredevops/components/llvm-project.yml, .azuredevops/components/rocMLIR.yml, .azuredevops/tag-builds/rocMLIR.yml
- Updating build flags for llvm-project to support another pipeline to work with aomp repos.
- Added support for rocMLIR component.
- Removed MIVisionX python dependency script and leveraged existing dependencies template.
=> External CI Tag Build Updates for Three Repos

CHANGELOG.md, RELEASE.md, tools/autotag/templates/rocm_changes/6.1.1.md
This PR removes HIPIFY's 6.1.1 changelog as it has been moved to 6.1.2
=> Remove hipify from 6.1.1 changelog

docs/what-is-rocm.rst
This PR updates the What is ROCm? page to remove RCP which is no longer maintained.
=> Update What is ROCm?: remove RCP from components and change repo links to ROCm docs

.azuredevops/components/hipRAND.yml
For next phase of external CI project, use pipeline artifacts instead of apt install. Providing hipRAND as example for rest of team to follow.
=> hipRAND: use azure pipeline artifacts instead of apt install

.github/CODEOWNERS
As documented in the link below, patterns ending with "/*" do not include further nested files and folders. Desired behaviour is to catch these further nested files and folders.
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners
=> CODEOWNERS nested folders pattern

docs/what-is-rocm.rst
Follow-up to #3129. Change ROCR-Runtime link to Intersphinx link.
=> Change ROCR-Runtime to relative link

docs/what-is-rocm.rst
Cherry-pick #3143 and #3129 into docs branches
=> Fix links to component docs in What is ROCm?

docs/what-is-rocm.rst
Cherry-pick https://github.com/ROCm/ROCm/pull/3143 and https://github.com/ROCm/ROCm/pull/3129 into docs branches
=> Fix links to component docs in What is ROCm? (6.1.0)

.azuredevops/components/aomp-extras.yml, .azuredevops/components/aomp.yml, .azuredevops/tag-builds/aomp-extras.yml, .azuredevops/tag-builds/aomp.yml, .azuredevops/templates/steps/artifact-download.yml, .azuredevops/templates/steps/dependencies-rocm.yml
Separate tag-build pipelines for aomp and aomp-extras to unblock other work.
=> External CI pipelines for openmp-extras repos

docs/reference/gpu-arch-specs.rst
As requested in another PR, this completes and adds the glossary back to the hardware specification table, and rephrases some of the descriptions.
=> Re-add glossary to hardware specification table

CHANGELOG.md, RELEASE.md, tools/autotag/templates/rocm_changes/6.1.1.md
This PR adds missed ROCm SMI notes to the consolidated changelog.
=> Fix ROCm SMI changelog

.azuredevops/ci-builds/aomp.yml
aomp build is not triggered by changes to aomp repo, but by updates to llvm-project and ROCR-Runtime, so trigger definition can remain in ROCm/ROCm repo.
=> Special pipeline for aomp with latest source

.azuredevops/components/rdc.yml, .azuredevops/components/rocBLAS.yml, .azuredevops/components/rocPRIM.yml, .azuredevops/templates/steps/artifact-download.yml, .azuredevops/templates/steps/dependencies-rocm.yml
rocBLAS: [AOCL gcc 4.2 for newer builds, use AOCL aocc 4.1 for 6.1.0 tag](https://github.com/ROCm/rocBLAS/blob/develop/clients/CMakeLists.txt#L119)
rocPRIM: incorrect compiler path
rdc: amdsmi
**_Logs of successful builds_**
**rocBLAS**
- [tag-build](https://dev.azure.com/rocm-ci/ROCm-CI/_build/results?buildId=1398&view=logs&j=97ce699c-40dd-5ae9-b9e5-e645874cb04a)
- [staging](https://dev.azure.com/rocm-ci/ROCm-CI/_build/results?buildId=1397&view=logs&j=97ce699c-40dd-5ae9-b9e5-e645874cb04a)
**rocPRIM**
- [tag-build](https://dev.azure.com/rocm-ci/ROCm-CI/_build/results?buildId=1399&view=logs&j=23986c94-575d-52f0-82b6-2a50ff31b4d4)
- [staging](https://dev.azure.com/rocm-ci/ROCm-CI/_build/results?buildId=1402&view=logs&j=23986c94-575d-52f0-82b6-2a50ff31b4d4)
**rdc**
- …
=> Some new external CI dependencies for latest source on default branches

.readthedocs.yaml
These are causing RTD builds to time out
=> Disable PDF on 6.1.0

.azuredevops/components/hipBLASLt.yml, .azuredevops/components/hipSPARSELt.yml, .azuredevops/templates/steps/dependencies-cmake-latest.yml
Template with bash commands to update cmake with snap. Ubuntu apt tool only has up to version 3.22, while snap can install 3.28. Use template for two components that want updated cmake with latest source on their default branches.
- [hipBLASLt](https://dev.azure.com/ROCm-CI/ROCm-CI/_build/results?buildId=1460&view=logs&j=00131318-001f-5906-71a1-f3ec7b45eb0a)
- [hipSPARSELt](https://dev.azure.com/ROCm-CI/ROCm-CI/_build/results?buildId=1461&view=logs&j=8073db15-de3f-58b2-17da-8a189bfd1bbe)
=> External CI: updated cmake dependencies

.azuredevops/components/MIOpen.yml
Attempts with latest source shows CMake error, searching for rocprofiler-register.
=> MIOpen External CI: Add rocprofiler-register dependency

.azuredevops/components/rocSPARSE.yml
rocSPARSE depends on rocBLAS, but it still builds without it and just throws a cmake warning. This PR adds rocBLAS into rocmDependencies.
Old build warning:
https://dev.azure.com/ROCm-CI/ROCm-CI/_build/results?buildId=1317&view=logs&j=b335d58d-d817-50f2-cd88-76ba01a68267&t=6e9ead50-31a2-5bcc-39ce-48fea8e7df2e&l=136
New build:
https://dev.azure.com/ROCm-CI/ROCm-CI/_build/results?buildId=1549&view=logs&j=b335d58d-d817-50f2-cd88-76ba01a68267&t=6e9ead50-31a2-5bcc-39ce-48fea8e7df2e&l=57
=> External CI: Add rocBLAS dependency to rocSPARSE

docs/compatibility/compatibility-matrix.rst, docs/reference/gpu-arch-specs.rst, docs/sphinx/static/css/rocm_custom.css
Makes the [Operating Systems](https://rocm.docs.amd.com/projects/install-on-linux/en/latest/reference/system-requirements.html) link appear in the table
Directly adds the header as text, to replace the :header: directive
=> Fix first link in compatibility matrix table

docs/reference/gpu-arch-specs.rst, docs/sphinx/static/css/rocm_custom.css
Quick fix to make the first row of tables visible again. Side-effect: removes sticky headers in tables.
---
* Fix first link in compatibility matrix table
* Revert "Fix first link in compatibility matrix table"
This reverts commit 069c5c116adf93245a1ce40d03021550c7c4e841.
* Remove sticky header and unused css
* Remove container from hardware specs matrix
---------
=> docs/6.1.2: Fix first link in compatibility matrix table (#3239)

docs/compatibility/compatibility-matrix.rst, docs/what-is-rocm.rst
TODO: update rocr_debug_agent links to intersphinx link when https://github.com/ROCm/rocr_debug_agent/pull/9 is merged.
=> Update links in compat matrix and what-is-rocm

docs/compatibility/compatibility-matrix.rst, docs/what-is-rocm.rst
* Update links in compat matrix and what-is-rocm
* Tensorflow -> TensorFlow
* Remove extra lines
* Revert "Remove extra lines"
This reverts commit 607c4323ac77fc120bcbcf3183cbf70cff12073a.
ROCm Debug Agent
=> docs/6.1.2: Update links in compat matrix and what-is-rocm (#3253)

.azuredevops/ci-builds/aomp.yml
Previous filter was not triggering this CI pipeline when ROCm-Runtime build was triggered from a pipeline completion trigger of llvm-project.
=> Remove branch filter for aomp pipeline trigger

.azuredevops/components/rocSPARSE.yml
Pipeline with two new tarball: https://dev.azure.com/ROCm-CI/ROCm-CI/_build/results?buildId=1789&view=results
=> External CI: Package rocSPARSE matrices for testers to consume

docs/compatibility/compatibility-matrix.rst
This PR removes the AOMP compiler from the compatibility matrix. No other changes.
=> Remove AOMP from compatibility matrix

docs/reference/gpu-arch-specs.rst, docs/sphinx/static/css/rocm_custom.css
Hotfix compatibility matrix table due to updated `pydata-sphinx-theme` requirement in 7a9ef99.
=> docs/6.1.0: Fix first link in compatibility matrix table (#3239)

docs/reference/gpu-arch-specs.rst, docs/sphinx/static/css/rocm_custom.css
Hotfix compatibility matrix table due to updated `pydata-sphinx-theme` requirement in 4040178.
=> docs/6.1.1: Fix first link in compatibility matrix table (#3239)

docs/compatibility/compatibility-matrix.rst, docs/how-to/llm-fine-tuning-optimization/profiling-and-debugging.rst, docs/reference/rocm-tools.md, docs/what-is-rocm.rst
* Fix link to debug agent in what-is-rocm
* ROCm --> ROCR
add index
* ROCR --> ROCr
* Change ROCm Debug Agent to ROCr Debug Agent in docs
=> Update link to ROCr Debug Agent to docs portal (#3303)

.azuredevops/components/rocprofiler.yml
Successful pipeline build with changes https://dev.azure.com/ROCm-CI/ROCm-CI/_build/results?buildId=2064&view=logs&j=4cbbbbe6-e3e9-50e2-34c4-5262ef5a7519
This is with latest amd-staging branch source of rocprofiler. In the future, we need to add some logic to pick up the latest .deb file from https://repo.radeon.com/rocm/misc/aqlprofile/ubuntu-22.04/ and to remove some of the hard-coded strings tied to version number in this yaml file.
=> External CI: Update aqlprofile binary used for rocprofiler

.azuredevops/components/rocm-examples.yml
rocm-examples builds successfully without ROCM_PATH and AMDGPU_TARGETS flags: https://dev.azure.com/ROCm-CI/ROCm-CI/_build/results?buildId=2348&view=logs&j=423f97a6-a742-5c36-b7f1-f5792f130520
=> External CI: remove redundant rocm-examples build flags

docs/compatibility/compatibility-matrix.rst
* Add RHEL 9.4 to compat matrix
* add rhel 9.4 footnote in compat matrix
=> docs/6.1.0: Add RHEL 9.4 to compat matrix (#3332)

docs/compatibility/compatibility-matrix.rst
* Add RHEL 9.4 to compat matrix
* add rhel 9.4 footnote in compat matrix
=> docs/6.1.1: Add RHEL 9.4 to compat matrix (#3332)

.azuredevops/components/hipSPARSE.yml
hipSPARSE requires matrices with the .bin extension for tests. I verified this works by manually downloading the matrices tar file and extracted the contents.
=> Uploading matrices as a tar file along with the hipSPARSE

docs/index.md
This PR removes unnecessary the `sd-text-black` class from cards on the home page.
- This lets the text colour in those cards switch between black and white in light mode and dark mode, respectively.
=> Fix card text color in index

.azuredevops/components/composable_kernel.yml
Add cmake flag to build instance only, since tests for different architectures cannot be built together.
Change pool to ultra and increase time limit to 3.5 hours.
=> Change composable_kernel CI pipeline to build for all architectures

docs/how-to/llm-fine-tuning-optimization/single-gpu-fine-tuning-and-inference.rst
Updated to correctly use the `--showproductname` flag.
Prior flag of `-showproductname` was not valid.
=> Update single-gpu-fine-tuning-and-inference.rst with correct `amd-smi` flag

.azuredevops/components/MIOpen.yml
Adding the hipBLASLt dependency to MIOpen.yml.
=> External CI: updated MIOpen dependencies

.azuredevops/templates/steps/artifact-download.yml, .azuredevops/templates/steps/dependencies-rocm.yml
Adds all externally building ROCm component pipelines and their Azure IDs. Also includes support for extracting components into Azure ephemeral storage at `/mnt` instead of `Agent.BuildDirectory`
Cherry picked from nightly branch so other components can start using these pipelines.
=> External CI: Add all current component pipeline IDs

.azuredevops/components/MIOpen.yml
Add hipBLAS dependency to MIOpen to fix build errors
Successful build log: https://dev.azure.com/ROCm-CI/ROCm-CI/_build/results?buildId=2991&view=logs&j=88ba0832-789b-5bb9-0dd5-a1a7441d06cc
=> External CI: Add hipBLAS to MIOpen

.azuredevops/components/MIOpen.yml, .azuredevops/components/ROCmValidationSuite.yml
Lately, /rocm/llvm has been moved to /rocm/lib/llvm, which breaks ROCmValidationSuite pipeline. As a temporary solution, create a symlink to /rocm/lib/llvm folder
Successful build with latest llvm-project: https://dev.azure.com/ROCm-CI/ROCm-CI/_build/results?buildId=3058&view=logs&j=a9dd7315-711f-5623-6d52-e9ce616061c5
In the long term, the install script of llvm-project should be change to /rocm/lib/llvm and we need to modify all pipelines' cmake flags to adapt that.
=> External CI: Add symlink to lib/llvm folder for ROCmValidationSuite

.azuredevops/components/hipBLASLt.yml
Build and install gtest, lapack, and hipBLAS-common for hipBLASLt pipeline.
hipBLAS-common is a new repo for code used for both hipBLAS and hipBLASLt. hipBLAS doesn't seem to actually pull in hipBLAS-common just yet, so this PR only includes hipBLASLt. Also, we may want to create a separate pipeline for hipBLAS-common in the future.
https://github.com/ROCm/hipBLAS-common
Successful build: https://dev.azure.com/ROCm-CI/ROCm-CI/_build/results?buildId=3214&view=results
=> External CI: build hipBLASLt external dependencies

.azuredevops/components/composable_kernel.yml
CK build count increased from 700 to 827. Increasing the time limit accordingly
=> External CI: Increase composable_kernel pipeline time limit

.azuredevops/components/hipBLASLt.yml, .azuredevops/templates/steps/build-cmake.yml
Since we moved from building gfx90a to gfx942, the build size for hipBLASLt was greatly increased (<19 GB to 58 GB) and was exceeding the VM storage capacity. This PR moves the build directory to ephemeral storage mounted at `/mnt`, and also creates a new parameter for build-cmake.yml to specify where the source code is located. The timeout limit is also increased to 100 minutes.
Successful build: https://dev.azure.com/ROCm-CI/ROCm-CI/_build/results?buildId=3686&view=logs&j=00131318-001f-5906-71a1-f3ec7b45eb0a
=> External CI: move hipBLASLt build directory to ephemeral storage

.azuredevops/components/MIOpen.yml, .azuredevops/variables-global.yml
Creates a variable for a new medium build pool with 2 TB OS disks and sets hipBLASLt to use it. Going forward, this should be the preferred way to resolve pipeline storage issues.
Successful build: https://dev.azure.com/ROCm-CI/ROCm-CI/_build/results?buildId=3746&view=results
=> External CI: move hipBLASLt to new large disk pool

.azuredevops/nightly/rocm-nightly.yml
This job collects the latest builds from all component pipelines and packages them into a single tarball. It runs daily at 07:30 UTC (03:30 EDT). 
Previous test runs: https://dev.azure.com/ROCm-CI/ROCm-CI/_build?definitionId=152
=> External CI: ROCm nightly builds

.azuredevops/components/rocFFT.yml
Fixes build failures caused by missing shared library `libdrm_amdgpu.so`
Successful build: https://dev.azure.com/ROCm-CI/ROCm-CI/_build/results?buildId=4318&view=results
=> External CI: add libdrm-dev package to rocFFT

.azuredevops/components/hipBLASLt.yml
Increases the time limit to 5 hours. All pools now have increased OS storage, so keep it in the medium pool and stop building under `/mnt`.
Successful build: https://dev.azure.com/ROCm-CI/ROCm-CI/_build/results?buildId=4523&view=results
=> External CI: increase hipBLASLt build timeout and storage

.azuredevops/nightly/pytorch.yml, .azuredevops/patches/pytorch/0001-ROCm-CI-patches.patch, .azuredevops/templates/steps/preamble.yml
Passing build job (non-scheduled version) can be found here
https://dev.azure.com/ROCm-CI/ROCm-CI/_build/results?buildId=4458&view=results
Produces a 1677 MB wheel file for gfx942 that includes latest default branch builds of ROCm software stack and the latest default branch build of upstream pytorch.
Will create versions for other combinations of GPU target, ROCm branch, and upstream pytorch branch.
=> External CI Build Job for Pytorch WHL

docs/how-to/tuning-guides/mi300x/workload.rst
change from absolute link to intersphinx link
=> Use intersphinx link to rocr debug agent

.azuredevops/components/roctracer.yml, .azuredevops/templates/steps/artifact-download.yml, .azuredevops/templates/steps/artifact-upload.yml, .azuredevops/templates/steps/dependencies-rocm.yml
Adding support for parallel build jobs where the only difference is the singular GPU target. This allows nightly packaging jobs to pick and choose based on GPU target to reduce download size.
To accommodate this new feature producing multiple artifacts for a component, added support for a file filter when downloading a ROCm component using the format "componentName:fileFilter".
Sample build log: https://dev.azure.com/rocm-ci/ROCm-CI/_build/results?buildId=4897&view=logs&j=aace0673-15c3-5d68-a50e-725354a1b253
Note that llvm-project is specified with filter amd-staging (i.e., llvm-project:amd-staging in the ROCm dependency array) to test out the file filter when set and the other components do not set a file filter to test base case.
=> External CI: Parallel per GPU jobs and file filters

.azuredevops/nightly/pytorch.yml
Skip redundant step of compressing wheel file into a tarball and publish the wheel file explicitly.
Build log with test run: https://dev.azure.com/rocm-ci/ROCm-CI/_build/results?buildId=4898&view=logs&j=970c8651-ba54-51fd-dcbf-513da2c9c2ce
=> External CI: Nightly pytorch packaging

docs/compatibility/compatibility-matrix.rst, docs/conceptual/ai-pytorch-inception.md, docs/how-to/deep-learning-rocm.rst, docs/how-to/llm-fine-tuning-optimization/model-acceleration-libraries.rst, docs/how-to/llm-fine-tuning-optimization/multi-gpu-fine-tuning-and-inference.rst, docs/how-to/llm-fine-tuning-optimization/single-gpu-fine-tuning-and-inference.rst, docs/how-to/rocm-for-ai/install.rst, docs/how-to/system-optimization/mi300a.rst, docs/how-to/system-optimization/mi300x.rst, docs/how-to/system-optimization/w6000-v620.md
Intersphinx links need to be updated due to https://github.com/ROCm/rocm-install-on-linux/pull/169/files#diff-45ae04487cf5c756c45df6508ae24d237c8f2cde0ec78079b5e2c4eaab2d8fae
=> Fix intersphinx links

.azuredevops/templates/steps/artifact-download.yml
Corrects the capitalization for ROCgdb, should be the last typo we have in the default branch list.
Successful nightly build, all components are found and downloaded:
https://dev.azure.com/ROCm-CI/ROCm-CI/_build/results?buildId=4946&view=results
=> External CI: fix ROCgdb component name

docs/conceptual/gpu-arch/mi250.md
=> Fix typo for TFLOPs metric in MI250 architecture page

.azuredevops/components/composable_kernel.yml, .azuredevops/components/hipSPARSELt.yml
hipSPARSELt does not support gfx90a according to its CMakeLists.txt composable_kernel build jobs are timing out, so adding 20 minutes more.
=> External CI: Adjustments from per-GPU job deployment.

.azuredevops/components/composable_kernel.yml
composable_kernel was failing with `clang++: error: no such include directory` ever since https://github.com/ROCm/composable_kernel/pull/1428 was merged.
https://dev.azure.com/ROCm-CI/ROCm-CI/_build/results?buildId=5002&view=logs&j=322274ab-3d3a-50ad-c943-92d9b62df04e&t=876c297d-6fa6-5973-3668-1768bae70b55&l=2765
This sets a HIP flag `-Wno-missing-include-dirs` to ignore that error as a temporary workaround, and CK seems to build fine.
Also increases the timeout limit to 3 hours for the gfx90a build. 
https://dev.azure.com/ROCm-CI/ROCm-CI/_build/results?buildId=5223&view=results
=> External CI: CK set -Wno-missing-include-dirs

.azuredevops/nightly/pytorch.yml
- Add support for gfx90a build.
- Adding versioning information to wheel file name.
- Change path for aotriton install to match pytorch repo.
Successful build log: https://dev.azure.com/rocm-ci/ROCm-CI/_build/results?buildId=5336&view=results
=> External CI Pytorch Job Updates

.azuredevops/components/HIP.yml
Adds OpenCL ICD libs to the HIP/clr pipeline: https://docs.amd.com/r/en-US/ug1393-vitis-application-acceleration/OpenCL-Installable-Client-Driver-Loader?tocId=9_OolfSP26w5RImnxKil8A
Also corrects the `rocmDependencies*` array names.
Build logs:
https://dev.azure.com/ROCm-CI/ROCm-CI/_build/results?buildId=5316&view=results
https://dev.azure.com/ROCm-CI/ROCm-CI/_build/results?buildId=5319&view=results
=> External CI: add OpenCL ICD libs to HIP/clr

.azuredevops/components/llvm-project.yml, .azuredevops/templates/steps/dependencies-rocm.yml
Includes temporary symbolic link for testing each part in isolation.
Changes separated into parts for producing and consuming the changes in tests per component.
=> External CI: Move llvm output folder to expected path (Part 1)

.azuredevops/components/llvm-project.yml, .azuredevops/templates/steps/dependencies-rocm.yml
Reverts ROCm/ROCm#3588
Downstream dependencies failing to find device-libs. Will debug further.
=> Revert "External CI: Move llvm output folder to expected path (Part 1)"

.azuredevops/components/HIP.yml
Recompilation of hip for AMD backend uses Microsoft-hosted agent, so no need to worry about VM costs if we re-build for any hipother repo changes.
=> Fix for hipother External CI pipeline

.azuredevops/components/rocDecode.yml
Adds `rocm-hip-runtime-dev` package from repo.radeon.com, and removes the `CMAKE_CXX_COMPILER` flag.
Fixes for: https://github.com/ROCm/rocDecode/pull/408
https://dev.azure.com/ROCm-CI/ROCm-CI/_build/results?buildId=5398&view=results
=> External CI: fix rocDecode CXX compiler

.wordlist.txt, docs/how-to/system-optimization/mi300a.rst
…… (#3587)
* Add a section on increasing memory allocation to the MI300A system optimization guide
* Addition to wordlist
* Change GB to GiB for consistency
* Standardize GiB/KiB spacing
* Minor wording changes
=> cherry-pick to docs/6.2.0: Add a section on increasing memory allocation to the MI300A system optimization guide

.azuredevops/components/MIOpen.yml, .azuredevops/templates/steps/artifact-download.yml
Enables latestFromBranch downloads for clr and rocMLIR, also corrects HIP/clr default branch names. 
Build log: https://dev.azure.com/ROCm-CI/ROCm-CI/_build/results?buildId=5519&view=results
=> External CI: enable clr and rocMLIR latestFromBranch downloads

docs/compatibility/compatibility-matrix.rst, docs/data/reference/compatibility-matrix-historical-6.0.csv
- Adds hipCC, rocAL, CLR
- Updates UCC version, incorporates https://github.com/ROCm/ROCm/pull/3520
- Rearrange to align with ROCm stack diagram
=> Update Compatibility Matrix for 6.2.0

.azuredevops/components/AMDMIGraphX.yml, .azuredevops/templates/steps/dependencies-rocm.yml
Adds a `skipLlvmSymlink` param into dependencies-rocm.yml to control whether to create the llvm-project symlink or not.
Fixed MIGraphX build:
https://dev.azure.com/ROCm-CI/ROCm-CI/_build/results?buildId=5782&view=results
=> External CI: make llvm-project symlink optional

.azuredevops/nightly/rocm-nightly.yml
Change ROCm nightly build to download components to default disk instead of `/mnt` since all pools now have increased base storage, fixes a build issue with the llvm symlink.
Successful run:
https://dev.azure.com/ROCm-CI/ROCm-CI/_build/results?buildId=5783&view=results
=> External CI: use root disk for ROCm nightly build

.azuredevops/components/copyHIP.yml
Adds the HIP pipeline ID and removes the `develop` branch name from copyHIP.yml. Fixes clr errors for automatically triggered runs.
Successful run:
https://dev.azure.com/ROCm-CI/ROCm-CI/_build/results?buildId=5813&view=results
=> External CI: fix HIP pipeline ID for copyHIP

docs/reference/api-libraries.md
Add rocPyDecode to ROCm libraries page
Consolidate Random numbers under Math libraries
Remove HIP card from ROCm libraries page
To be cherry-picked into 6.2.0 docs
=> Add rocPyDecode with other changes

.azuredevops/components/composable_kernel.yml
Increases build time for CK gfx90a builds.
=> External CI: Increase CK timeout to 4 hours

.azuredevops/components/AMDMIGraphX.yml, .azuredevops/components/ROCmValidationSuite.yml
Adds hipBLASLt and hipBLAS-common to MIGraphX and RVS to anticipate some PRs:
https://github.com/ROCm/AMDMIGraphX/pull/3371
https://github.com/ROCm/ROCmValidationSuite/pull/799
Also adds additional dependencies and an `AMDGPU_TARGETS` flag to resolve some MIGraphX cmake configuration warnings.
=> External CI: add hipBLASLt to MIGraphX and ROCmValidationSuite

.azuredevops/components/rocm-examples.yml
Resolves build failure for: https://github.com/ROCm/rocm-examples/pull/141
Also adds the AMDGPU_TARGETS flag to quiet a cmake warning.
https://dev.azure.com/ROCm-CI/ROCm-CI/_build/results?buildId=6032&view=results
=> External CI: add hipBLASLt + roc/hipFFT to rocm-examples

.azuredevops/components/llvm-project.yml, .azuredevops/components/rocBLAS.yml
- llvm-project should not use default symbolic link to llvm-project.
- rocBLAS now depends on hipBLASLt.
Passing build logs:
https://dev.azure.com/ROCm-CI/ROCm-CI/_build/results?buildId=6104&view=results
https://dev.azure.com/ROCm-CI/ROCm-CI/_build/results?buildId=6111&view=results
=> External CI: Build Fixes for llvm-project and rocBLAS

.azuredevops/components/rocm-examples.yml
Should fix running out of storage issues for gfx942.
=> External CI: move rocm-examples to medium build pool

docs/how-to/system-optimization/mi300a.rst
The original content incorrectly had `ttm` in path rather than `amdttm`.
=> Correct ttm to amdttm

docs/how-to/system-optimization/mi300a.rst
* Expand the section on changing thread affinity
* Clarify the methods for configuring allocatable memory settings
* Small correction
=> Cherry pick to docs/6.2.0: MI300A updates

.azuredevops/components/hipBLASLt.yml, .azuredevops/templates/steps/dependencies-rocm.yml
Fixes a hipBLASLt failure introduced by https://github.com/ROCm/hipBLASLt/pull/893
https://github.com/ROCm/hipBLASLt/pull/893/files#diff-cb27de26e92cd3dc56a24df9a28cad5693ef9123a74f2e20d1fde1d8aafe9c6eR37
Build log: https://dev.azure.com/ROCm-CI/ROCm-CI/_build/results?buildId=7007&view=results
A normal ROCm installation does have these symlinks:
```
/opt/rocm-6.2.0/bin$ ls -la | grep llvm/bin
lrwxrwxrwx 1 root root        24 Aug 15 13:59 amdclang -> ../lib/llvm/bin/amdclang
lrwxrwxrwx 1 root root        26 Aug 15 13:59 amdclang++ -> ../lib/llvm/bin/amdclang++
lrwxrwxrwx 1 root root        27 Aug 15 13:59 amdclang-cl -> ../lib/llvm/bin/amdclang-cl
lrwxrwxrwx 1 root root        28 Aug 15 13:59 amdclang-cpp -> ../lib/llvm/bin/amdclang-cpp
lrwxrwxrwx 1 root root        24 Aug 15 13:59 …
```
=> External CI: create symlinks for llvm binaries

.azuredevops/ci-builds/aomp.yml, .azuredevops/components/aomp.yml, .azuredevops/tag-builds/aomp.yml
Replace cmake calls with bash script calls to compile the components comprising openmp-extras.
Added inline comments to describe the bash scripts from aomp repo being executed.
Successful build at https://dev.azure.com/rocm-ci/ROCm-CI/_build/results?buildId=7229&view=results
=> External CI: Leverage aomp build scripts

docs/how-to/system-optimization/mi300a.rst
* Expand the section on changing thread affinity
* Clarify the methods for configuring allocatable memory settings
* Small correction
=> Cherry-pick to roc-6.2.x: MI300A updates

.wordlist.txt, docs/how-to/llm-fine-tuning-optimization/model-acceleration-libraries.rst
* Add FBGEMM/FBGEMM_GPU to the Model acceleration libraries page
* Add words to wordlist and fix a typo
* Add new sections for Docker and testing
* Incorporate comments from the external review
* Some minor edits and clarifications
* Incorporate further review coments and fix test section
* Add comment to test section
* Change git clone command for FBGEMM repo
* Change Docker command
* Changes from internal review
* Fix linting issue
=> Cherry pick to docs/6.2.1: Add FBGEMM/FBGEMM_GPU to the Model acceleration libraries page (#3659)

.azuredevops/components/rocm-core.yml
Due to ifdefs in some components, bump the version string for amd-staging builds.
=> External CI: Bump version string in rocm-core pipeline

.azuredevops/components/ROCR-Runtime.yml
Fixes a build failure introduced by: https://github.com/ROCm/ROCR-Runtime/commit/7e13b9e62fe0acd7966cd0a24dcfc7fcba6d65d7
Build log: https://dev.azure.com/ROCm-CI/ROCm-CI/_build/results?buildId=7418&view=results
=> External CI: build shared libs for ROCR-Runtime

.azuredevops/components/aomp.yml
Passing build log: https://dev.azure.com/rocm-ci/ROCm-CI/_build/results?buildId=7547&view=results
=> External CI: Copy aomp artifacts to llvm directory before tarball.

.azuredevops/components/composable_kernel.yml
- Test results are not parsed to be graphed in Azure reports.
- Added ccache to potentially improve build times, keyed against the date and hash based on amdclang++ binary.
Passing build log: https://dev.azure.com/rocm-ci/ROCm-CI/_build/results?buildId=7539&view=results
Log above temporarily removed gfx90a build to save on resources.
=> External CI: Add gfx942 testing for composable_kernel

.azuredevops/components/rocAL.yml, .azuredevops/templates/steps/test.yml
Also adds an extra step in test.yml to reload AMDGPU module to avoid occasional issues with opening /dev/kfd
Test logs: https://dev.azure.com/ROCm-CI/ROCm-CI/_build/results?buildId=7593&view=results (7 min)
=> External CI: rocAL tests & reload AMDGPU for tests

.azuredevops/components/rocm-examples.yml
Not sure why cmake now needs to be explicitly installed for this component, but this fixes a build error for https://github.com/ROCm/rocm-examples/pull/161: https://dev.azure.com/ROCm-CI/ROCm-CI/_build/results?buildId=7617&view=results
Successful build: https://dev.azure.com/ROCm-CI/ROCm-CI/_build/results?buildId=7684&view=results
=> External CI: add cmake to rocm-examples

.azuredevops/components/hipBLAS.yml, .azuredevops/components/rocBLAS.yml, .azuredevops/templates/steps/dependencies-aocl.yml
New template to make the downloaded AOCL version consistent between pipelines, currently only hipBLAS and rocBLAS use it.
Build logs:
https://dev.azure.com/ROCm-CI/ROCm-CI/_build/results?buildId=7599&view=results
https://dev.azure.com/ROCm-CI/ROCm-CI/_build/results?buildId=7600&view=results
=> External CI: create AOCL template

.azuredevops/components/rocMLIR.yml
The test job is compiling in parallel on the test system since the build job is building for shared library use.
=> External CI: Add smoke tests to rocMLIR

docs/how-to/llm-fine-tuning-optimization/model-quantization.rst
Users have been facing issues due to incomplete installation documentation.
See https://github.com/ROCm/bitsandbytes README
=> Add missing make command to bitsandbytes install commands

.azuredevops/components/rocm-examples.yml
Moves rocm-examples binaries into a new `rocm/examples` folder, and the test job just runs everything in that folder.
Build log: https://dev.azure.com/ROCm-CI/ROCm-CI/_build/results?buildId=7828&view=results
=> External CI: rocm-examples tests

.azuredevops/components/half.yml
Tried out test11, even on a more powerful VM. Test was tracking to take more than an hour. Settled for test03 for smoke tests.
https://dev.azure.com/rocm-ci/ROCm-CI/_build/results?buildId=7900&view=results
=> External CI: half component smoke test

docs/compatibility/precision-support.rst
The change in the link target is required due to changes in https://github.com/ROCm/rocRAND/pull/548.
=> Update link to rocRAND data type support

tools/autotag/README.md, tools/autotag/tag_script.py
Closes https://github.com/ROCm/ROCm/issues/3585
ie: add a prev release option to autotag script so that it does not have to start at 5.0.0
passing in the `--do-previous` flag would start from 5.0.0
pass in the `starting-versions=<a.b.c>` flag where a.b.c is the version to start from
=> Add starting-versions flag to autotag script

.azuredevops/templates/steps/dependencies-aqlprofile.yml
Changes aqlprofile tag-builds version as well as staging version to 6.2 since that's the latest release of aqlprofile available.
=> External CI: update aqlprofile to 6.2

.azuredevops/ci-builds/aomp.yml, .azuredevops/components/aomp.yml, .azuredevops/components/rocm-examples.yml, .azuredevops/templates/steps/artifact-download.yml
Guidance from Ethan Stewart on how to execute the smoke test, plus iterative runs to debug and identify extra environment changes required.
With latest amd-staging, 416/427 tests pass. [Log](https://dev.azure.com/rocm-ci/ROCm-CI/_build/results?buildId=8161&view=results)
=> External CI: aomp smoke test

.azuredevops/components/rccl.yml, .azuredevops/templates/steps/artifact-download.yml
`Standalone.RegressionTiming` test failure is known and has an internal ticket assigned.
Test logs:
https://dev.azure.com/ROCm-CI/ROCm-CI/_build/results?buildId=6928&view=logs&j=f1bf911a-d440-5cfc-a34f-33a9eaa69e16&t=b5507126-a70d-5e98-ee50-268cc9fc6e42&l=51427
=> External CI: rccl unit tests

.azuredevops/components/hipBLASLt.yml
- Add roctracer dependency to hipBLASLt build to address recent failures.
- Change build pool to ultra due to increased build times.
- Enable ccache to help with build times.
=> External CI: hipBLASLt roctracer dependency and ccache build

docs/how-to/rocm-for-ai/install.rst
Radeon does not match our release sequence, so we are using an absolute link to the 6.1.3 release here.
=> Fix Radeon link and point at R6.1.3 as absolute link

.azuredevops/components/hipBLAS.yml, .azuredevops/components/hipBLASLt.yml, .azuredevops/components/hipFFT.yml, .azuredevops/components/hipSPARSELt.yml, .azuredevops/components/rocWMMA.yml, .azuredevops/components/rpp.yml
Add roctracer dependency for hipBLAS and rocWMMA testing.
**_Build Logs_**
[hipBLAS](https://dev.azure.com/rocm-ci/ROCm-CI/_build/results?buildId=8443&view=results)
[hipBLASLt](https://dev.azure.com/rocm-ci/ROCm-CI/_build/results?buildId=8435&view=results)
[hipFFT](https://dev.azure.com/rocm-ci/ROCm-CI/_build/results?buildId=8436&view=results)
[hipSPARSELt](https://dev.azure.com/rocm-ci/ROCm-CI/_build/results?buildId=8437&view=results)
[rocWMMA](https://dev.azure.com/rocm-ci/ROCm-CI/_build/results?buildId=8444&view=results)
[rpp](https://dev.azure.com/rocm-ci/ROCm-CI/_build/results?buildId=8439&view=results)
=> External CI: Replace libomp-dev dependencies with aomp

.azuredevops/components/rocprofiler.yml
- v1 results are not parsed and graphed
- v2 results are parsed and graphed
[Passing Build Log](https://dev.azure.com/ROCm-CI/ROCm-CI/_build/results?buildId=8472&view=results)
=> External CI: Add rocprofiler v1 and v2 smoke tests

.azuredevops/components/ROCgdb.yml, .azuredevops/templates/steps/build-autotools.yml
- Since this is an autotools project and not cmake, build and test on gfx942 system instead of separating into two jobs. Pipeline time is short anyway.
- Follow public build instructions to update build flags and to incorporate ROCdbgapi.
- Results are not parsed and graphed, but the log contents are printed at the end. This was helpful for debugging and will be kept in the pipeline, as the make check-gdb command's output was not helpful on its own.
[Passing Build Log](https://dev.azure.com/ROCm-CI/ROCm-CI/_build/results?buildId=8477&view=results)
=> External CI: ROCgdb smoke tests

.azuredevops/components/rocPyDecode.yml
[Build Pipeline](https://dev.azure.com/rocm-ci/ROCm-CI/_build/results?buildId=8625&view=results)
Since testing is not affected by this change, testing was disabled in the pipeline to test the changes.
=> External CI: Publish wheel as artifact for rocPyDecode

.azuredevops/components/hip-tests.yml
Increases time to 4 hours since a previous run exceeded the limit
=> External CI: fix hip-tests symlink creation

.azuredevops/components/AMDMIGraphX.yml, .azuredevops/components/composable_kernel.yml
- Swap to default gcc on OS to resolve build errors from recent commits.
- Added libdnnl-dev dependency from iterative attempts with compiler change.
- Referred to the passing GitHub checks to observe the compilers that was used.
- Include jit lib in composable_kernel build for AMDMIGraphX dependency.
- [Passing Build Log of CK](https://dev.azure.com/ROCm-CI/ROCm-CI/_build/results?buildId=8932&view=results)
- [Passing Build Log of AMDMIGraphX pulling in above CK build](https://dev.azure.com/ROCm-CI/ROCm-CI/_build/results?buildId=8943&view=results)
=> External CI: AMDMIGraphX Build Fix

.azuredevops/components/ROCmValidationSuite.yml, .azuredevops/components/hipSPARSE.yml, .azuredevops/components/rocALUTION.yml, .azuredevops/components/rocBLAS.yml, .azuredevops/components/rocSPARSE.yml, .azuredevops/templates/steps/artifact-download.yml
Adds omniperf to the `allowPartiallySucceededBuilds` list as a component with known failing tests.
Adds roctracer as a test dependency to RVS, hipSPARSE, rocALUTION, rocBLAS, and rocSPARSE to resolve recent test failures for these components.
Successful rocBLAS build:
https://dev.azure.com/ROCm-CI/ROCm-CI/_build/results?buildId=8885&view=results
=> External CI: test fixes w/ roctracer, list omniperf as partially succeeding

.azuredevops/components/rpp.yml, .azuredevops/templates/steps/artifact-download.yml
Adds default, voxel, and audio tests for RPP. `Tensor_hip` tests are currently failing due to a linker error with OpenMP, compiler team is investigating.
Build log, default tests only (7 min):
https://dev.azure.com/ROCm-CI/ROCm-CI/_build/results?buildId=8881&view=results
=> External CI: rpp tests

.azuredevops/components/omnitrace.yml
omnitrace tests don't require a GPU and its ctest files aren't packaged, so it runs tests in the build step. 
Build logs (45 min): https://dev.azure.com/ROCm-CI/ROCm-CI/_build/results?buildId=9072&view=results
=> External CI: omnitrace tests

.azuredevops/components/hipTensor.yml
Adds a filter for `-extended` hipTensor tests to keep running time low, also changes from gtest to ctest parameters.
Test log:
https://dev.azure.com/ROCm-CI/ROCm-CI/_build/results?buildId=9203&view=results
=> External CI: filter out hipTensor extended tests

.azuredevops/components/rocPyDecode.yml
- Set values for expected environment variables.
- Accompanying changes required in rocPyDecode repo. Pull request will be made.
- [Pipeline build log](https://dev.azure.com/ROCm-CI/ROCm-CI/_build/results?buildId=9371&view=results) where wheel creation works. Testing was cancelled to save resources.
=> External CI: Fix rocPyDecode wheel creation

.azuredevops/components/rocprofiler.yml, .azuredevops/templates/steps/dependencies-aqlprofile.yml
Changes the aqlprofile template to programmatically get the deb package name for your Ubuntu version.
Switches the aqlprofile source for staging builds to https://repo.radeon.com/rocm/apt/latest/
Tag builds are sourced from https://repo.radeon.com/rocm/apt/latest/$TAGGED_RELEASE/ (TAGGED_RELEASE is an Azure var)
Example run:
https://dev.azure.com/ROCm-CI/ROCm-CI/_build/results?buildId=9762&view=results
=> External CI: programmatically get latest aqlprofile

.azuredevops/components/AMDMIGraphX.yml, .azuredevops/components/MIOpen.yml, .azuredevops/components/rocMLIR.yml, .azuredevops/components/rocm-examples.yml
rocm-examples now also builds on the test system so we can use ctest, and Azure can parse the test results.
The rocm-examples test job is not in parallel to the build job and requires it to pass first. Also changed AMDMIGraphX, MIOpen, and rocMLIR test jobs to have the same behaviour.
Build log:
https://dev.azure.com/ROCm-CI/ROCm-CI/_build/results?buildId=9725&view=results
=> External CI: use ctest for rocm-examples

.azuredevops/dependencies/boost.yml, .azuredevops/tag-builds/boost.yml, .azuredevops/templates/steps/dependencies-boost.yml, .azuredevops/variables-global.yml
Created template to download and extract the built products to a boost folder and call ldconfig on the folder.
Some ROCm components require a newer version of boost libraries than what can be obtained from the default ubuntu package manager sources, and the third-party sources are not 100% reliable.
[Pipeline Log](https://dev.azure.com/ROCm-CI/ROCm-CI/_build/results?buildId=10154&view=results)
=> External CI: Add pipeline to build upstream boost

docs/how-to/llm-fine-tuning-optimization/model-quantization.rst, docs/how-to/llm-fine-tuning-optimization/single-gpu-fine-tuning-and-inference.rst
Users should checkout `rocm_enabled_multi_backend` by default instead of `rocm_enabled` now.
https://github.com/ROCm/bitsandbytes
=> Update bitsandbytes default branch in docs

docs/reference/precision-support.rst
Very small PR to add a ref to the precision support table to link to it from other pages
Needed for https://github.com/ROCm/HIP/pull/3574
=> Documentation: Add reference to precision-support floating-point types

.azuredevops/components/MIOpen.yml, .azuredevops/templates/steps/dependencies-boost.yml
Updates MIOpen pipeline to use the Boost template, and removes some unused parameters from the Boost template.
Build log:
https://dev.azure.com/ROCm-CI/ROCm-CI/_build/results?buildId=10197&view=results
=> External CI: use Boost template for MIOpen

.azuredevops/components/rocprofiler-systems.yml, .azuredevops/tag-builds/rocprofiler-systems.yml, .azuredevops/templates/steps/artifact-download.yml, .azuredevops/templates/steps/dependencies-rocm.yml
Creating pipeline files for rocprofiler-systems in preparation for the rebranding: https://github.com/ROCm/rocprofiler-systems
The pipeline was largely copied from existing omnitrace files. The main difference was changing build flags from `-DOMNITRACE_*` to `-DROCPROFSYS_*`.
Pipeline ID vars will be added after this PR is merged and pipelines are created.
Build+test log:
https://dev.azure.com/ROCm-CI/ROCm-CI/_build/results?buildId=10205&view=results
=> External CI: create rocprofiler-systems pipeline

docs/how-to/system-optimization/mi100.md, docs/how-to/system-optimization/mi200.md, docs/how-to/system-optimization/mi300x.rst, docs/how-to/system-optimization/w6000-v620.md, tools/autotag/templates/highlights/5.3.0.md
Per kernel-parameters.txt, there is no "on" option for amd_iommu. While intel_iommu has it, amd_iommu is automatically on unless specified otherwise. For more info, see these 2 links:
https://www.kernel.org/doc/Documentation/admin-guide/kernel-parameters.txt https://github.com/torvalds/linux/blob/75aa74d52f43e75d0beb20572f98529071b700e5/drivers/iommu/amd/init.c#L3481
=> docs: Remove invalid amd_iommu=on parameter

docs/how-to/system-optimization/mi100.md, docs/how-to/system-optimization/mi200.md, docs/how-to/system-optimization/mi300x.rst, docs/how-to/system-optimization/w6000-v620.md, tools/autotag/templates/highlights/5.3.0.md
- #3919 
Per kernel-parameters.txt, there is no "on" option for amd_iommu. While intel_iommu has it, amd_iommu is automatically on unless specified otherwise. For more info, see these 2 links:
https://www.kernel.org/doc/Documentation/admin-guide/kernel-parameters.txt https://github.com/torvalds/linux/blob/75aa74d52f43e75d0beb20572f98529071b700e5/drivers/iommu/amd/init.c#L3481
Signed-off-by: Kent Russell <kent.russell@amd.com>
(cherry picked from commit 74333b667d34ce9d90726572533b28059f3fe5b6)
=> docs: Remove invalid amd_iommu=on parameter (#3919)

.azuredevops/components/hipBLASLt.yml
- [Catalyst](https://github.com/ROCm/hipBLASLt/pull/1250/files#diff-fee2e6f068b33fca3a1dc49392de8848dbf05c3f4632b680abb1052523e5a30fR35)
- [Failing Build Log After Catalyst](https://dev.azure.com/ROCm-CI/ROCm-CI/_build/results?buildId=10567&view=results)
- [Passing Build Log With Catalyst and This PR](https://dev.azure.com/ROCm-CI/ROCm-CI/_build/results?buildId=10574&view=results)
=> External CI: hipBLASLt build now requires python packaging module

.azuredevops/nightly/pytorch.yml
https://github.com/pytorch/pytorch/pull/138103
Note that there are new build failures due to upstream changes that incorporates CK back-end, but this PR's changes should allow the nightly builds to at least track when that build failure is resolved.
=> External CI: Moved location of upstream pytorch build scripts

.azuredevops/components/rocMLIR.yml, .azuredevops/components/roctracer.yml
rocMLIR tests are failing and leaking processes, leaving the system in a bad state. Skipping over the tests for now.
Also adds `AMDGPU_TARGETS` flag to roctracer to fix a build warning.
Sample rocMLIR failure:
https://dev.azure.com/ROCm-CI/ROCm-CI/_build/results?buildId=10579&view=results
Sample rocRAND hang due to prior rocMLIR test:
https://dev.azure.com/ROCm-CI/ROCm-CI/_build/results?buildId=10522&view=results
=> External CI: disable rocMLIR tests

.azuredevops/components/rocDecode.yml
Fixes a build failure introduced by: https://github.com/ROCm/rocDecode/commit/e463cbd0f2a1311b871013088ff013c126418bbe
Build log:
https://dev.azure.com/ROCm-CI/ROCm-CI/_build/results?buildId=10945&view=results
=> External CI: rocDecode add libva-amdgpu-dev dependency

.azuredevops/components/ROCR-Runtime.yml, .azuredevops/components/ROCmValidationSuite.yml, .azuredevops/components/amdsmi.yml, .azuredevops/components/rocAL.yml, .azuredevops/components/rocDecode.yml, .azuredevops/components/rocm_bandwidth_test.yml, .azuredevops/components/rocm_smi_lib.yml, .azuredevops/components/rocminfo.yml, .azuredevops/components/roctracer.yml, .azuredevops/templates/steps/gpu-diagnostics.yml
Adds steps to enumerate GPU devices in the diagnostics template. 
`amdsmi`, `rocm_smi_lib`, `rocminfo`, and `ROCR-Runtime` pipelines will skip running rocminfo, as it isn't appropriate for those to have a rocminfo dependency.
=> External CI: enumerate GPUs in gpu-diagnostics

.azuredevops/nightly/pytorch.yml
To support recent upstream changes and issues observed.
These changes can be seen to unblock execution in this job: https://dev.azure.com/rocm-ci/ROCm-CI/_build/results?buildId=11015&view=results
However, recent stack changes seem to cause tests to hang, which is not caused by pipeline code.
Full build job functionality is dependent on my upstream pytorch PR to merge, as the linked jobs had an extra block to force CK submodule to update. My pending PR changes the submodule upstream.
=> External CI: pytorch pipeline updates

docs/reference/gpu-arch-specs.rst
There was inconsistency in the CU count where 250X lists per GCD, but 250 does not. In keeping with the per GCD convention, it would make sense to list CU and L2 cacher per XCD for MI300 as well.
=> Improve consistency of the gpu-arch-specs table.

.azuredevops/components/Tensile.yml
[Log output](https://dev.azure.com/rocm-ci/ROCm-CI/_build/results?buildId=11100&view=logs&j=8ffe2db8-e69f-5c49-4c8e-6ac009c1283b&t=a74b2696-0bdd-5ef0-3840-ebc0a84dd54e) shows it is looking for aqlprofile during test execution.
=> External CI: Add aqlprofile to Tensile test dependencies

.azuredevops/templates/steps/gpu-diagnostics.yml
GPU diagnostics should not create build warnings, so suppress their exit codes with `|| true`.
=> External CI: suppress GPU diag warnings

.azuredevops/components/rocprofiler-compute.yml, .azuredevops/tag-builds/rocprofiler-compute.yml, .azuredevops/templates/steps/artifact-download.yml, .azuredevops/templates/steps/dependencies-rocm.yml
Renamed pipeline files, added staging and mainline branch names, and gfx download filters for omniperf -> rocprofiler-compute.
=> External CI: rocprofiler-compute pipeline files

.azuredevops/components/MIOpen.yml, .azuredevops/components/hip-tests.yml, .azuredevops/components/rocAL.yml, .azuredevops/components/rocm-examples.yml
Disables reloading AMDGPU for the few components which had it. It doesn't work in Docker, and the Docker agents should not need this anyways.
=> External CI: disable reload AMDGPU

.azuredevops/components/rocBLAS.yml
Should fix recent build fails introduced by: https://github.com/ROCm/rocBLAS/commit/bb98ee0bf79152033bf8ccefc643d41d2fe7d710
=> External CI: add roctracer to rocBLAS deps

.azuredevops/components/rocDecode.yml, .azuredevops/components/rocPyDecode.yml, .azuredevops/templates/steps/dependencies-other.yml
- Only target container with access to first device
- Install the amd va packages, not the generic dev packages
- Ensure pybind11-dev is uninstalled before the package manager install steps
=> External CI: decode test changes

RELEASE.md, docs/compatibility/compatibility-matrix-historical-6.0.csv, docs/compatibility/compatibility-matrix.rst
Add missed Omniperf changelog. See https://github.com/ROCm/rocprofiler-compute/pull/461.
Also fix RDC version numbers in release notes and compatibility matrix.
=> Add Omniperf changelog to 6.2.1 release notes and fix RDC version in compat matrix

.azuredevops/components/rocprofiler-systems.yml
To fix build failure: https://dev.azure.com/ROCm-CI/ROCm-CI/_build/results?buildId=13364&view=results
=> External CI: add aomp as rocprofiler-systems dependency

RELEASE.md
Fix links to not use preview and point to specific ver.
=> Fix links in release notes 6.2.4

.azuredevops/components/AMDMIGraphX.yml, .azuredevops/components/hip-tests.yml, .azuredevops/components/omnitrace.yml, .azuredevops/components/rocAL.yml, .azuredevops/components/rocDecode.yml, .azuredevops/components/rocprofiler-compute.yml, .azuredevops/components/rocprofiler-systems.yml, .azuredevops/components/rpp.yml, .azuredevops/templates/steps/test.yml
- Test failures will now trigger an build error rather than a warning
- Known flaky/failing tests are exempt, will continue to have `continueOnError: true`
- Exempt components listed under `allowPartiallySucceededBuilds`
- `continueOnError` can't be set at runtime, so the component list must be a parameter
- Post-test clean up steps now have `condition: always()`
- Removed AMDGPU reloading, not applicable in Docker
=> External CI: allow test failures to present as failures on Github

.azuredevops/components/ROCR-Runtime.yml
Disable rdmatest and rocrtstFunc.Memory_Max_Mem as they don't work in Docker containers
=> External CI: disable rdmatest and rocrtstFunc.Memory_Max_Mem

.azuredevops/components/llvm-project.yml
To fix `clang-20: error: cannot find HIP runtime; provide its path via '--rocm-path', or pass '-nogpuinc' to build without HIP runtime` when building comgr.
Adds a `HIP_PATH` env var pointing to the ROCm home. Reference: https://github.com/ROCm/ROCm/issues/3380#issuecomment-2237132073
Successful build: https://dev.azure.com/ROCm-CI/ROCm-CI/_build/results?buildId=13861&view=results
=> External CI: fix comgr build

.azuredevops/components/Tensile.yml
Tensile's tox test takes 1 hour ± a few minutes, so increase the time limit to 90 mins.
=> External CI: increase Tensile test timeout to 90 mins

.azuredevops/components/MIOpen.yml, .azuredevops/templates/steps/miopen-get-ck-build.yml
Changes MIOpen's pipelines to build/pull requirements as specified in its requirements.txt file
- Test timeout increased to 90 mins to accommodate extra build time
- Downloads CK artifacts from an existing run to save time
- The referenced CK commits are merges from CK/develop to CK/amd-develop
- These commits are not present on CK/develop, which is what Ex-CI builds for
- So it instead gets the parent commit, which is a normal commit present on both develop and amd-develop
- Then it calls the Github API to get the check-runs for that parent commit, and looks for an Azure pipelines run
- Finally, download the build artifacts from that run
- If anything can't be found, instead download artifacts from the latest successful CK build
- A warning will be thrown if this happens
Test run, both …
=> External CI: use MIOpen's requirements.txt

.azuredevops/components/rocprofiler-compute.yml, .azuredevops/components/rocprofiler-systems.yml
To help in finding required ROCm binaries when running tests.
=> External CI: add ROCM_PATH to rocprofiler-systems/compute

.azuredevops/components/rocprofiler-compute.yml
- Adds rocm-smi as a dependency
- Increased timeout to 2 hours, tests take ~90 mins
- Sets ROCM_PATH var for ctest
There's currently test failures related to MI300 roofline files, this is a component issue and will be fixed on their side.
Test log: https://dev.azure.com/ROCm-CI/ROCm-CI/_build/results?buildId=15079&view=results
=> External CI: rocprofiler-compute test fixes

.azuredevops/components/ROCR-Runtime.yml, .azuredevops/components/hipBLAS.yml
- Specifies release build for ROCR-Runtime
- Adds PyYaml to hipBLAS pip dependencies
=> External CI: ROCR build release, hipBLAS test fix

.azuredevops/components/MIOpen.yml
- Specifies MIOpen dependencies to be installed under `$(Agent.BuildDirectory)/miopen-deps`
- Prevents deps from being installed under `/usr/local`, which can cause package conflict issues
- Adds libsqlite3-dev
Build log: https://dev.azure.com/ROCm-CI/ROCm-CI/_build/results?buildId=15347&view=results
=> External CI: set MIOpen dependencies install path

.azuredevops/templates/steps/manifest.yml
Medium pool agents don't have jq installed by default.
=> External CI: install jq in manifest template

.azuredevops/components/aomp.yml
Fixes build failure introduced in: https://github.com/ROCm/aomp/commit/d3f5619574b2d005cd4b17653a010d7b54888d42#diff-a3a93d987efaf295420509949be227d55c0dc97e1b89415ec0b442c44bb9c547
Build log: https://dev.azure.com/ROCm-CI/ROCm-CI/_build/results?buildId=15755&view=results
=> External CI: AOMP rename flang/llvm-legacy to flang/llvm-classic

.azuredevops/components/aomp.yml, .azuredevops/nightly/rocm-nightly.yml, .azuredevops/templates/steps/manifest.yml
- Corrects location of omp.h header file for symlink creation
- Refer: https://dev.azure.com/ROCm-CI/ROCm-CI/_build/results?buildId=15814&view=logs&j=96f6ff47-56da-531a-589c-8e03d8a52c15&t=9dbec5b4-3462-5a97-7d43-c8ac1937474e&l=18
- Adds manifest creation to the nightly job
- Adds always conditions to manifest steps to create them even for failed builds
AOMP build log: https://dev.azure.com/ROCm-CI/ROCm-CI/_build/results?buildId=15826&view=results
=> External CI: AOMP symlink fix and manifest additions

.azuredevops/components/rocJPEG.yml, .azuredevops/tag-builds/rocJPEG.yml, .azuredevops/templates/steps/artifact-download.yml, .azuredevops/variables-global.yml
- Created `tag-builds` and `components` pipeline files
- Largely similar to the rocDecode pipeline
- Added staging and mainline branch names to `artifact-download.yml`
- Updated repo.radeon version to 6.3
Build log: https://dev.azure.com/ROCm-CI/ROCm-CI/_build/results?buildId=16181&view=results
=> External CI: create pipeline files for rocJPEG

docs/sphinx/_toc.yml.in
(cherry picked from commit 1a4d54a4f12b83f75b4c78e5afa0c8cce62eabaa)
=> remove programming guide from TOC (#4116)

docs/how-to/tuning-guides/mi300x/workload.rst
(cherry picked from commit 78f9adc6ec8db7eed747eaf84312de36c9791381)
=> [6.3] fix rccl hip streams section in workload tuning guide (#4140)

.azuredevops/components/MIOpen.yml
- Exclude lone, consistently failing MIOpen test.
- test_rnn_seq_api is the only ctest failure, so let's filter it out for now to easily identify new failures.
- [Passing build log](https://dev.azure.com/rocm-ci/ROCm-CI/_build/results?buildId=16643&view=results)
=> External CI: MIOpen Test Parameters

.azuredevops/components/rocPyDecode.yml, .azuredevops/templates/steps/dependencies-rocm.yml
- Modifying the HIP shared libraries installed, to follow the Linux symbolic link convention, resolves test failures in rocPyDecode.
- Failing tests before this change: https://dev.azure.com/ROCm-CI/ROCm-CI/_build/results?buildId=16689&view=results
- Passing tests after this change: https://dev.azure.com/ROCm-CI/ROCm-CI/_build/results?buildId=16785&view=results
=> External CI: HIP shared library symlinks for rocPyDecode

.azuredevops/components/llvm-project.yml
Disabling spirv for comgr to fix errors.
Successful build: https://dev.azure.com/ROCm-CI/ROCm-CI/_build/results?buildId=16819&view=results
=> External CI: llvm project comgr disable spirv

.wordlist.txt, docs/compatibility/compatibility-matrix-historical-6.0.csv, docs/compatibility/compatibility-matrix.rst
Changes KFD to kernel-mode GPU compute driver in two places in the docs.
=> Change reference to kernel-mode GPU compute driver in ROCm

.wordlist.txt, docs/compatibility/compatibility-matrix-historical-6.0.csv, docs/compatibility/compatibility-matrix.rst
* Change reference to kernel-mode GPU compute driver in ROCm
* More changes for kernel-mode terminology
* Fix linting
(cherry picked from commit 04fdc08328f9d5ba23829050083c5f345020aa85)
=> Cherry-pick to docs/6.3.0: Change reference to kernel-mode GPU compute driver in ROCm (#4147)

.wordlist.txt, docs/compatibility/compatibility-matrix-historical-6.0.csv, docs/compatibility/compatibility-matrix.rst
* Change reference to kernel-mode GPU compute driver in ROCm
* More changes for kernel-mode terminology
* Fix linting
(cherry picked from commit 04fdc08328f9d5ba23829050083c5f345020aa85)
=> Cherry-pick to roc-6.3.x: Change reference to kernel-mode GPU compute driver in ROCm (#4147)

.azuredevops/nightly/pytorch.yml
- Recent vision compilation has been failing, and debugging hasn't been fruitful in finding cause.
- Should unblock nightly job to at least build and test pytorch while debug effort continues after the holidays.
- pytorch build and test is unblocked by temporarily patching the composable_kernel submodule on upstream pytorch to latest develop, until that submodule is updated to have explicit cast for hneg.
- Build log: https://dev.azure.com/ROCm-CI/ROCm-CI/_build/results?buildId=17344&view=results
- Test pass rate of 99.8% matches historical trend on the system.
=> External CI: Add toggle for torchvision build and test

.azuredevops/components/rdc.yml
Fix for RDC build failure introduced in https://github.com/ROCm/rdc/commit/7c91a07a4318c03197da27021a711585d00fb77e
https://dev.azure.com/ROCm-CI/ROCm-CI/_build/results?buildId=17781&view=results
=> External CI: add rocprofiler-sdk to RDC

.azuredevops/components/rocm_smi_lib.yml
Adds `libdrm-dev` package to fix a build error introduced by https://github.com/ROCm/rocm_smi_lib/commit/6f51cd651e4116b04c2df6a2afe8859558bdba66
Successful build log:
https://dev.azure.com/ROCm-CI/ROCm-CI/_build/results?buildId=17777&view=results
=> External CI: add libdrm-dev package to rocm_smi_lib

.azuredevops/components/composable_kernel.yml, .azuredevops/components/rccl.yml, .azuredevops/components/rpp.yml, .azuredevops/templates/steps/miopen-get-ck-build.yml
RCCL:
https://dev.azure.com/ROCm-CI/ROCm-CI/_build/results?buildId=17896&view=results
- Added `libdrm-dev` to packages
- Sorted apt packages
RPP:
https://dev.azure.com/ROCm-CI/ROCm-CI/_build/results?buildId=17900&view=results
- Freeze NIFTI to v3.0.1
- Change `AMDGPU_TARGETS` flag to `GPU_TARGETS` to resolve deprecation warning
- Sorted apt packages
MIOpen:
- Fixed incorrect Azure API parameters to prevent downloading failed CK builds
composable_kernel:
- Increased test timeout to 90 mins
=> External CI: small fixes for RCCL, RPP, MIOpen, CK

docs/conf.py
(cherry picked from commit eafa2de533c054240bcb608e367654d424e408b5)
=> [docs/6.3.1] remove `windows` from pytorch compat header (#4219)

LICENSE, docs/about/license.md, docs/conf.py
This PR changes the links to ROCm project licenses to the repositories' default branches. This ensures that the links contain the most current versions of the files.
=> Fix target branches in list of licenses

README.md
These were encountered while debugging
https://github.com/ROCm/ROCm/issues/4190
- There is no manifest (-m) for ROCm 6.3.1 in the tools/rocm-build folder 
- Changed the rocm version to 6.3.0 to avoid immediate build failure. This would be better remedied by adding a ROCm 6.3.1 XML in the tools/rocm-build folder
- The manifest is not specified in the first instance of "Downloading the ROCm source code", but it is in "Build ROCm from source". 
- Without the correct manifest, subsequent build instructions will fail as the ROCm/ROCm directory doesn't get pulled by the default manifest. It's unclear why these two otherwise identical commands are duplicated and have this discrepancy
=> Fix build instruction errors:

docs/how-to/rocm-for-hpc/index.rst
Added the following applications to the Using ROCm for HPC page application list:
Ansys Fluent
Amber
DevitoPRO
OpenFOAM (OpenFOAM with PETSc Solver)
PeleC
PETSc
Simcenter Star-CCM+ (Siemens StarCCM+)
Echelon (Stone Ridge Technology ECHELON)
Cherry-picked from https://github.com/ROCm/ROCm/pull/4066
=> HPC application list updated 6.3.0(#4066)

docs/how-to/rocm-for-hpc/index.rst
Added the following applications to the Using ROCm for HPC page application list:
Ansys Fluent
Amber
DevitoPRO
OpenFOAM (OpenFOAM with PETSc Solver)
PeleC
PETSc
Simcenter Star-CCM+ (Siemens StarCCM+)
Echelon (Stone Ridge Technology ECHELON)
Cherry-picked from https://github.com/ROCm/ROCm/pull/4066
=> HPC application list updated 6.3.1 (#4066)

.azuredevops/components/rocAL.yml
Adds `libdlpack-dev` and `libsndfile1-dev` packages to resolve https://github.com/ROCm/rocAL/issues/258.
Also adds `GPU_TARGETS` build flag.
Build logs: https://dev.azure.com/ROCm-CI/ROCm-CI/_build/results?buildId=18031&view=logs&j=82dddf77-1810-596a-155f-4c5d5ecc99c3&t=0510f471-8adb-52df-cfd3-7d6ab5c4c1b5
=> External CI: add missing rocAL functionalities

.azuredevops/components/hipBLASLt.yml
hipBLASLt uses internal defaults for the code object version, and upcoming updates improve the robustness of this option when unspecified. This PR simply removes the parameter from the cmake options and leaves it up to hipBLASLt/TensileLite to determine the best default.
=> Remove code object version at build in hipBLASLt

.azuredevops/components/ROCmValidationSuite.yml, .azuredevops/components/rocWMMA.yml
Fixes build failures for RVS and rocWMMA due to missing `libdrm`.
Also changes `AMDGPU_TARGETS` to `GPU_TARGETS` for rocWMMA.
rocWMMA: https://dev.azure.com/ROCm-CI/ROCm-CI/_build/results?buildId=18332&view=results
RVS: https://dev.azure.com/ROCm-CI/ROCm-CI/_build/results?buildId=18333&view=results
=> External CI: add libdrm-dev to RVS, rocWMMA

.azuredevops/components/hipBLASLt.yml
Fixes error in hipBLASLt CMake flag step: `TypeError: canonicalize_version() got an unexpected keyword argument 'strip_trailing_zero'`
Reference: https://github.com/pypa/setuptools/issues/4483#issuecomment-2236339726
Build log (current `code-object-version` errors are unrelated and are under investigation): https://dev.azure.com/ROCm-CI/ROCm-CI/_build/results?buildId=18551&view=results
=> External CI: upgrade packaging to >=22.0 for hipBLASLt

docs/compatibility/compatibility-matrix.rst, docs/compatibility/ml-compatibility/jax-compatibility.rst, docs/compatibility/ml-compatibility/pytorch-compatibility.rst, docs/compatibility/ml-compatibility/tensorflow-compatibility.rst, docs/conceptual/ai-pytorch-inception.md, docs/how-to/programming_guide.rst, docs/how-to/rocm-for-hpc/index.rst, docs/index.md, docs/reference/api-libraries.md, docs/reference/precision-support.rst, docs/reference/rocm-tools.md, docs/release/versions.md
The following PR addresses the warnings (and some errors) from the sphinx build output:
- Duplicate target names
- Some links were edited to have unique names according to the context
- Some links were fixed to ensure the same target
- In the case of the links under the tensorflow-compatibility.rst page, the following [solution](https://www.tarantool.io/en/doc/latest/contributing/docs/sphinx-warnings/#duplicate-explicit-target-name) was used to ensure visual consistency rather than applying a unique name
- `:orphan:` was added to files that are not listed within the main toctree, but are accessible via other pages
- Some errors were produced due to labels being placed outside `{grid-item-card}`; those labels have been moved into the cards
- In `docs/conceptual/ai-pytorch-inception.md`, …
=> Docs: resolve warnings from sphinx build output

docs/how-to/rocm-for-ai/scale-model-training.rst
Fix link due to moved files in https://github.com/meta-llama/llama-cookbook/commit/ae010af7d86d2d4589250ba57ed519356f8e5d25
=> Fix link to Llama recipes

.azuredevops/components/rocprofiler-sdk.yml, .azuredevops/templates/steps/dependencies-other.yml, .azuredevops/templates/steps/test.yml
Enables running rocprofiler-sdk tests. Not all the tests seem to be installed into the build package, so rocprof-sdk is rebuilt for the test job. The current failing tests are consistent with internal CI, so adding it to the allowed failures list.
Adds an parameter for dependencies-other to register repo.radeon.com as an apt repo. Also sets `continueOnError` for the Firefox version freeze in case it is not installed.
Build log:
https://dev.azure.com/ROCm-CI/ROCm-CI/_build/results?buildId=18989&view=results
=> External CI: run rocprofiler-sdk tests

.azuredevops/components/rocAL.yml
Adds rocDecode as a test dependency for rocAL for PR: https://github.com/ROCm/rocAL/pull/253. Test job now requires `firstRenderDeviceAccess` as a result. 
Also sorted the rocmDeps list.
Build log: https://dev.azure.com/ROCm-CI/ROCm-CI/_build/results?buildId=19074&view=results
=> External CI: add rocDecode to rocAL test deps

.azuredevops/components/hipSPARSELt.yml
Adds roctracer as a dependency for hipSPARSELt. Also removes the `Tensile_CODE_OBJECT_VERSION` flag to align with new Tensile changes.
Build log:
https://dev.azure.com/ROCm-CI/ROCm-CI/_build/results?buildId=19157&view=results
=> External CI: add roctracer to hipSPARSELt

docs/how-to/rocm-for-ai/scale-model-training.rst
(cherry picked from commit 8dd99fe3a4217b656f0fc4685c77b50e3f027e69)
=> [docs/6.3.1] fix link to llama cookbook (#4269)

.azuredevops/components/rocprofiler-systems.yml
Adding rocDecode to rocprofiler-systems for its new `videodecode` functionalities. 
The rccl-* test failures are known, however the other test failures are unexpected. I'm making this PR now just to get rocprof-sys building again and since the `videodecode` tests themselves are passing. And I'll follow up on the failures at a later time.
Build log:
https://dev.azure.com/ROCm-CI/ROCm-CI/_build/results?buildId=19004&view=logs&j=375c53a2-01e1-5d86-2fdb-8a9532908181&t=a34ac966-e730-59b6-a1c8-2c6474689cc1&l=143065
=> External CI: add rocDecode to rocprofiler-systems

.github/workflows/linting.yml, .spellcheck.local.yaml
This PR depends on https://github.com/ROCm/rocm-docs-core/pull/1100
Once the above is merged in, the `linting.yml` file will be updated to target the proper branch.
This PR adds a local spellcheck file that adds all C++ files from `include/hip` for the C++ spellchecking workflow (for now the spellchecking ignores all block and line comments).
=> Add spellcheck configuration

docs/how-to/rocm-for-ai/fine-tuning/index.rst, docs/how-to/rocm-for-ai/index.rst, docs/how-to/rocm-for-ai/inference/index.rst, docs/how-to/rocm-for-ai/training/index.rst, docs/index.md, docs/sphinx/_toc.yml.in
* Add ToC and index links to the AI Developer Tutorials
* Change link positioning
* Change wording
(cherry picked from commit d401b5f1521c4b2db5b39300c3bf8585f67a53b1)
=> Cherry-pick to roc-6.3.x: Add ToC and index links to the AI Developer Tutorials (#4312)

docs/how-to/rocm-for-ai/inference/vllm-benchmark.rst
Fix merge conflict markers in vllm-benchmark.rst. For some reason, this only happened when syncing develop --> roc-6.3.x --> docs/6.3.2.
#4318 addresses roc-6.3.x
=> [docs/6.3.2] Fix merge conflict markers in vllm-benchmark.rst

docs/how-to/rocm-for-ai/fine-tuning/index.rst, docs/how-to/rocm-for-ai/index.rst, docs/how-to/rocm-for-ai/inference/index.rst, docs/how-to/rocm-for-ai/training/index.rst, docs/index.md, docs/sphinx/_toc.yml.in
* Add ToC and index links to the AI Developer Tutorials
* Change link positioning
* Change wording
(cherry picked from commit d401b5f1521c4b2db5b39300c3bf8585f67a53b1)
=> Cherry-pick to docs/6.3.2: Add ToC and index links to the AI Developer Tutorials (#4312)

.azuredevops/components/rocprofiler-sdk.yml, .azuredevops/components/rocprofiler-systems.yml
Adds required ROCm dependencies to rocprofiler-sdk and rocprofiler-systems for their new VCN tracing capabilities.
rocprofiler-sdk log:
https://dev.azure.com/ROCm-CI/ROCm-CI/_build/results?buildId=19993&view=results
rocprofiler-systems log:
https://dev.azure.com/ROCm-CI/ROCm-CI/_build/results?buildId=19994&view=results
=> Ex CI: rocprof-sdk & rocprof-systems VCN tracing dependencies

.azuredevops/components/rocDecode.yml, .azuredevops/components/rocJPEG.yml, .azuredevops/components/rocm-core.yml, .azuredevops/components/rocminfo.yml, .azuredevops/components/rocprofiler-sdk.yml, .azuredevops/components/rocprofiler-systems.yml, .azuredevops/dependencies/half560.yml, .azuredevops/templates/steps/dependencies-aqlprofile.yml, .azuredevops/templates/steps/dependencies-other.yml, .azuredevops/templates/steps/docker-container.yml, .azuredevops/variables-global.yml
- Changes all references to repo.radeon.com to use the `REPO_RADEON_VERSION` global variable
- repo.radeon.com can sometimes have inconsistent behaviour across geographical regions due to caching issues, this var allows for blanket version rollbacks while the caches are being fixed
- Renames deps-other's `registerRadeon` flag to `registerROCmPackages` to match with Docker creation template
- Removes manual repo registration from rocDecode and rocJPEG, now use `registerROCmPackages`
- Removes some unused/redundant global variables:
```
DOCKER_IMAGE_NAME
LATEST_DOCKER_VERSION
KEYRING_VERSION
LAST_RELEASE
REIMAGE_ORG
REIMAGE_REPO
```
rocprofiler-sdk logs:
https://dev.azure.com/ROCm-CI/ROCm-CI/_build/results?buildId=20070&view=results
rocDecode logs: …
=> Ex CI: add REPO_RADEON_VERSION as a global variable, clean up other variables

.azuredevops/components/hipBLASLt.yml, .azuredevops/components/rocBLAS.yml
Added `ROCM_PATH` env var to rocBLAS to fix a Tensile build issue, and changed the compiler used from hipcc to amdclang.
Also cleaned up some unused vars in rocBLAS and hipBLASLt pipelines to align with each other.
hipBLASLt logs:
https://dev.azure.com/ROCm-CI/ROCm-CI/_build/results?buildId=20218&view=results
rocBLAS logs:
https://dev.azure.com/ROCm-CI/ROCm-CI/_build/results?buildId=20219&view=results
=> Ex CI: add ROCM_PATH to rocBLAS

docs/about/license.md
ROCm Bandwidth Test uses the MIT license.
=> Fix ROCm Bandwidth Test license type

.azuredevops/components/rocWMMA.yml
- Set the value of this expected variable to fix build failures.
- [Build Log](https://dev.azure.com/ROCm-CI/ROCm-CI/_build/results?buildId=20299&view=results)
=> External CI: rocWMMA ROCM_PLATFORM_VERSION value set

.azuredevops/components/ROCR-Runtime.yml, .azuredevops/components/rocprofiler-systems.yml
- Add rocm_smi_lib dependency to rocprofiler-systems.
- Explicitly set OPENCL_INC_DIR in ROCR-Runtime test job.
=> External CI: Fix failures for rocprofiler-systems and ROCR-Runtime

.azuredevops/components/ROCR-Runtime.yml
- Removing the creation of expected folders and symbolic links as workaround to get the test components compiling.
- Set the only OpenCL build flag affecting the build.
- TODO: Add logic to automatically determine the version of clang that has the lib directory. For example, 21.
- [Passing Build Log](https://dev.azure.com/ROCm-CI/ROCm-CI/_build/results?buildId=20626&view=results)
=> External CI: Fix ROCR common test suite build

.azuredevops/components/rccl.yml, .azuredevops/components/rocminfo.yml
Fixes a build failure caused by a change in `hipify-perl`'s install directory. https://github.com/ROCm/HIPIFY/pull/1855
Also sets `registerROCmPackages` for rocminfo docker creation.
https://dev.azure.com/ROCm-CI/ROCm-CI/_build/results?buildId=20729&view=results
=> Ex CI: remove manual hipify-perl chmod from rccl

.azuredevops/components/MIOpen.yml
Sets `ROCM_PATH` env for MIOpen tests for https://github.com/ROCm/MIOpen/pull/3391
Change cmake flag from `AMDGPU_TARGETS` to `GPU_TARGETS`
Build log:
https://dev.azure.com/ROCm-CI/ROCm-CI/_build/results?buildId=20849&view=results
=> Ex CI: set ROCM_PATH for MIOpen tests

.azuredevops/templates/steps/miopen-get-ck-build.yml
The CK promotion process changed slightly, and the previous method of finding parent commits no longer works for MIOpen. Since CI is now enabled for CK's amd-develop branch (https://github.com/ROCm/composable_kernel/pull/1859), we can directly search for the commit called out in [requirements.txt](https://github.com/ROCm/MIOpen/blob/develop/requirements.txt)
If no valid build or artifact is found, it will continue to fall back to the latest successful CK build.
Sample run:
https://dev.azure.com/ROCm-CI/ROCm-CI/_build/results?buildId=20948&view=logs&j=832f3a36-34cd-5de6-6cd3-6744a08875be&t=cf727a4d-891e-5a95-0f3a-52baaaad2efb
[A compiler build fix](https://github.com/ROCm/composable_kernel/commit/78195cccad673825f046523e84c503de7e741ef1) has not been promoted to amd-develop yet, so the …
=> Ex CI: adjust MIOpen's CK fetch script to no longer find parent commits

.azuredevops/components/rpp.yml
Adds rocm-cmake as a build dep for https://github.com/ROCm/rpp/pull/516
A longer-term fix for the manual `ROCM_PLATFORM_VERSION` flag setting is being worked on [in this branch](https://github.com/ROCm/ROCm/tree/amd/danielsu/rocm-cmake-ROCM_PLATFORM_PATH)
Sample run (build job passed, pending test job results):
https://dev.azure.com/ROCm-CI/ROCm-CI/_build/results?buildId=20987&view=results
=> Ex CI: add rocm-cmake to rpp build job

.azuredevops/components/rocPyDecode.yml
- Change owner after running install steps, for packaging and upload.
- Necessary to support changes in https://github.com/ROCm/rocPyDecode/pull/160
- [Passing Build Log](https://dev.azure.com/ROCm-CI/ROCm-CI/_build/results?buildId=21096&view=results)
=> rocPyDecode External CI: Use sudo for cmake install step

.azuredevops/variables-global.yml
Update to ROCm 6.3.3
Sample build w/ repo registration and aqlprofile dependency:
https://dev.azure.com/ROCm-CI/ROCm-CI/_build/results?buildId=21367&view=results
=> Ex CI: update to 6.3.3

.azuredevops/components/rocm_smi_lib.yml, .azuredevops/templates/steps/dependencies-rocm.yml
[rocprofiler-compute](https://github.com/ROCm/rocprofiler-compute)'s default branch has changed to `develop`.
Also adds pkg-config to rocm_smi_lib to fix a build error:
https://dev.azure.com/ROCm-CI/ROCm-CI/_build/results?buildId=21365&view=results
=> Ex CI: change rocprof-compute default branch to develop

docs/compatibility/ml-compatibility/pytorch-compatibility.rst, docs/compatibility/ml-compatibility/tensorflow-compatibility.rst
* update PyTorch docker inventories in compatibility doc
* update TF docker inventories in compatibility doc
* update text to rocm 6.3.3
(cherry picked from commit 934767322badada214038b20c363252c14a00bc7)
=> [docs/6.3.3] Update PT and TF docker inventories in compatibility docs (#4415)

.azuredevops/components/roctracer.yml
[Passing Build Job](https://dev.azure.com/rocm-ci/ROCm-CI/_build/results?buildId=21934&view=results)
=> External CI: Add libdrm_amdgpu to roctracer dependencies

.azuredevops/components/llvm-project.yml
- Add flang to built projects.
- Upgrade build VM to account for additional project.
- Temporarily ignore a test case for debug info, which is not a high priority in External CI.
- [Passing Build Log](https://dev.azure.com/rocm-ci/ROCm-CI/_build/results?buildId=22103&view=results)
=> External CI: llvm-project updates

.azuredevops/components/rocm-cmake.yml, .azuredevops/templates/steps/dependencies-rocm.yml, .azuredevops/templates/steps/test.yml
Updates branch names for rocminfo and rocm-examples.
Fixes all rocm-cmake tests to now pass, removed it from the list of allowed failures.
- Downgrade to cmake 3.20.5 to fix simple-test
- Skip version-parent as it expects to be run in a git repo, which is not the case here
Build log: https://dev.azure.com/ROCm-CI/ROCm-CI/_build/results?buildId=22194&view=logs&j=65d9a8c4-c7f3-5147-6903-54915f681079&t=399c18ed-247c-533c-c28a-e58e44181d65
=> Ex CI: fix rocm-cmake tests, update component branch names

.azuredevops/components/hipBLASLt.yml
To resolve hipBLASLt tests exceeding one hour and timing out.
=> Ex CI: increase hipBLASLt test timeout to 2 hours

.gitignore, docs/compatibility/ml-compatibility/jax-compatibility.rst, docs/compatibility/ml-compatibility/pytorch-compatibility.rst, docs/compatibility/ml-compatibility/tensorflow-compatibility.rst, docs/conf.py, docs/extension/version-ref.py
The goal of this PR is to prevent margins of error where library versions across multiple files aren't updated correctly. A directive can be used in the page such as `:version-ref:``hipCUB latest`` or `:version-ref:``hipCUB 6.3.1``
=> Docs: use custom directive to reference library versions

.azuredevops/templates/steps/build-cmake.yml, .azuredevops/templates/steps/dependencies-rocm.yml, .azuredevops/templates/steps/manifest.yml
- Adds `printDiskSpace` parameter to build-cmake.yml to toggle printing disk space
- Changes ROCr-Runtime branch from `amd-master` to `amd-mainline`
- Edits the manifest HTML file to look a bit nicer when viewing the plaintext
rocminfo build without disk space prints:
https://dev.azure.com/ROCm-CI/ROCm-CI/_build/results?buildId=22732&view=logs&j=50b3bdbe-86d2-54db-afce-a3fd8fdae30c
=> Ex CI: make disk space print optional, small ROCr and manifest tweaks

.azuredevops/components/MIOpen.yml, .azuredevops/components/hipTensor.yml, .azuredevops/components/rocm-cmake.yml, .azuredevops/templates/steps/test.yml
Some component tests were creating massive amounts of logs and were basically unviewable in the browser. Removes the `-VV` flag for CTest invocations to cut down on this.
rocWMMA test logs (previously was >1GB in size):
https://dev.azure.com/ROCm-CI/ROCm-CI/_build/results?buildId=22714&view=logs&j=1a546237-c6f8-5834-1a77-9ff8fa7092ce&t=35c315dc-7dae-5501-67bb-b3d2e02c50ca
=> Ex CI: make component CTests nonverbose

.azuredevops/components/ROCmValidationSuite.yml, .azuredevops/components/rocMLIR.yml, .azuredevops/components/rocPyDecode.yml, .azuredevops/components/rocprofiler-compute.yml
- rocMLIR
- Install hip-python pip package, other python deps
- For https://github.com/ROCm/rocMLIR/pull/1762
- rocPyDecode
- Change hip-python installation method to match rocMLIR
- ROCmValidationSuite
- Matrix-ize the test conf file directory to not be hardcoded for MI300X
- Sample run: https://dev.azure.com/ROCm-CI/ROCm-CI/_build/results?buildId=22884&view=results
- Run is based off https://github.com/ROCm/ROCmValidationSuite/pull/908 since it contains a critical build fix
- rocprofiler-compute
- Removed a long-deprecated `ROCPROFCOMPUTE_ARCH_OVERRIDE` var that was being set for tests
=> Ex CI: fixes for rocMLIR, rocPyDecode, RVS, rocprof-compute

docs/how-to/rocm-for-ai/inference-optimization/workload.rst
=> Fix "VGPR" typo in workload tuning guide

docs/how-to/rocm-for-ai/inference-optimization/workload.rst
* Fix "VGPR" typo in workload tuning guide
=> [docs/6.3.3] Fix "VGPR" typo in workload tuning guide (#4484)

docs/data/how-to/rocm-for-ai/inference/vllm-benchmark-models.yaml, docs/how-to/rocm-for-ai/inference/deploy-your-model.rst, docs/how-to/rocm-for-ai/inference/llm-inference-frameworks.rst, docs/how-to/rocm-for-ai/inference/vllm-benchmark.rst, docs/how-to/rocm-for-ai/training/benchmark-docker/megatron-lm.rst, docs/sphinx/_toc.yml.in
* add links to performance results
words
* change "performance validation" to "performance testing"
* update vLLM docker 3/11
* add previous versions
add previous versions
* fix llama 3.1 8b model repo name
* words
(cherry picked from commit 9b2ce2b63465d23ac2022a5f1ef798b790dc4602)
=> [docs/6.3.3] Update vLLM performance Docker docs (#4491)

.azuredevops/components/composable_kernel.yml, .azuredevops/components/hipBLASLt.yml, .azuredevops/components/rdc.yml, .azuredevops/components/rocprofiler-sdk.yml
- RDC
- Updated gRPC to 1.67.1
https://dev.azure.com/ROCm-CI/ROCm-CI/_build/results?buildId=23353&view=results
- hipBLASLt
- Increased test timeout to 3 hours
- rocprof-sdk
- Added roctracer and libva-dev
- Added rocminfo to PATH
- Added GPU diags step before tests
https://dev.azure.com/ROCm-CI/ROCm-CI/_build/results?buildId=23354&view=results
- composable_kernel
- Increased test timeout to 3 hours
=> Ex CI: fixes for RDC, rocprof-sdk, hipBLASLt, CK

.azuredevops/components/MIOpen.yml, .azuredevops/components/MIVisionX.yml, .azuredevops/components/ROCgdb.yml, .azuredevops/components/Tensile.yml, .azuredevops/components/aomp.yml, .azuredevops/components/hip-tests.yml, .azuredevops/components/hipBLASLt.yml, .azuredevops/components/hipfort.yml, .azuredevops/components/rdc.yml, .azuredevops/components/rocDecode.yml, .azuredevops/components/rocJPEG.yml, .azuredevops/components/rocMLIR.yml, .azuredevops/components/rocPyDecode.yml, .azuredevops/components/rocprofiler-systems.yml, .azuredevops/components/rocprofiler.yml, .azuredevops/components/rpp.yml
Removed the creation of `/opt/rocm` symlinks from nine components. Removed the deletion of symlinks in test jobs, since the test environments are no longer persistent across jobs, and added a comment wherever the deletions used to be.
Symlinks removed from:
- MIOpen
- hipBLASLt
- rocPyDecode
- rocJPEG
- rocDecode
- rdc
- rpp
- rocprofiler-systems
- rocprofiler
Components that still use symlinks are:
- rocMLIR
- Tensile
- aomp
- MIVisionX
- hipfort
- ROCgdb
- hip-tests
- pytorch
=> Ex CI: remove /opt/rocm symlinks from nine components
