README.md
based on `4.6.0-kfd-compute-rocm-rel-1.4-16`
=> fixed wrong path in opencl compiler call (opencl-rocm-dev 1.2.0)

README.md, default.xml
Release ROCm 1.7 information to master branch.
=> ROCm 1.7.0

README.md, default.xml
Reverts RadeonOpenCompute/ROCm#530
=> Revert "Update to Roc 1.9.0"

default.xml
Signed-off-by: Icarus Sparry <icarus.sparry@amd.com>
=> Fix 773 - duplicated part of manifest

default.xml
Move branch forward to recent PR fix.
=> Fix llvm and lld 2.3 tags for opencl and hcc (#770)

default.xml
=> ROCm release 3.3 Manifest File

default.xml
=> 3.10 : Manifest Files

.github/CODEOWNERS
Currently, adding myself as the codeowner. Additional users are needed to reflect ROCm teams.
=> Adding a CODEOWNERS file

docs/deploy.md, docs/deploy/docker.md, docs/how_to/magma_install/magma_install.md
=> Add docker deployment guide

docs/quick_start.md
=> Quick Start Linux: Add RHEL and SLES instructions, minor touch-ups to Ubuntu

docs/release/support_matrix.md
=> Added support matrices

docs/index.md
It would be great to also provide readers a pointer to the public AMD lab notes series
=> Added reference to AMD lab notes

docs/reference/openmp/openmp.md
=> Fixing openmp link

docs/reference/openmp/openmp.md
- Resolves #2089
- Style: 80 column width
=> Update openmp documentation

.github/workflows/linting.yml, .wordlist.txt, RELEASE.md, docs/.sphinx/_toc.yml.in, docs/deploy/linux/quick_start.md, docs/how_to/tuning_guides/index.md, docs/how_to/tuning_guides/mi100.md, docs/how_to/tuning_guides/mi200.md, docs/reference/framework_compatibility/framework_compatibility.md, docs/reference/gpu_libraries/linear_algebra.md, tools/autotag/templates/changelog.jinja
Closes #2136, closes #2135, closes #2133, closes #2131
Also fixes the CI executing twice in certain MRs.
=> Various docs fixes

docs/reference/openmp/openmp.md
Updated the link for supported GPUs from absolute to relative "(../../release/gpu_os_support.md#gpu-support-table)"
=> Update openmp.md links

docs/conf.py, docs/sphinx/requirements.in, docs/sphinx/requirements.txt
closes https://github.com/RadeonOpenCompute/ROCm/pull/2184
closes https://github.com/RadeonOpenCompute/rocm-docs-core/issues/214
=> Update doc requirements and suppress duplicate main doc link

docs/how_to/tuning_guides/mi200.md, docs/reference/gpu_libraries/rand.md
Miscellaneous fixes based on internal feedback.
=> Team-feedback

docs/deploy/linux/index.md, docs/deploy/linux/install_overview.md, docs/deploy/linux/installer/install.md, docs/deploy/linux/installer/uninstall.md, docs/deploy/linux/installer/upgrade.md, docs/deploy/linux/os-native/index.md, docs/deploy/linux/os-native/uninstall.md, docs/deploy/linux/os-native/upgrade.md, docs/sphinx/_toc.yml.in
- revert distro command installation -> package manager installation
- move description of installer script to common section
- updates to the installer script installation page
- other misc fixes
=> Install updates

docs/deploy/linux/quick_start.md
=> Remove package pin from quick start quide

CHANGELOG.md, RELEASE.md, default.xml, tools/autotag/tag_script.py, tools/autotag/templates/changelog.jinja, tools/autotag/templates/rocm_changes/5.5.0.md, tools/autotag/templates/rocm_changes/5.6.0.md
=> ROCm 5.6 Changelog Updates

docs/deploy/linux/installer/install.md, docs/deploy/linux/os-native/install.md, docs/deploy/linux/os-native/upgrade.md, docs/deploy/linux/quick_start.md, docs/release/gpu_os_support.md
- add them to the os support table
- add install instructions for them
=> Add RHEL 8.8 and 9.2 as supported distributions for 5.6

docs/deploy/linux/installer/install.md, docs/deploy/linux/os-native/install.md, docs/deploy/linux/os-native/uninstall.md, docs/deploy/linux/os-native/upgrade.md, docs/deploy/linux/prerequisites.md, docs/deploy/linux/quick_start.md, docs/how_to/tuning_guides/mi100.md, docs/how_to/tuning_guides/mi200.md, docs/release/gpu_os_support.md
- https://github.com/RadeonOpenCompute/ROCm/commit/ff6cfe959cfa77571bab39c8fa940649106683b8 and https://github.com/RadeonOpenCompute/ROCm/commit/dffc8d68e5602284a99e24c67678ecb4e7f091a4 has fixes that are relevant to not just 5.6, hopefully this branch gets merged back to develop, otherwise it will need to be cherry-picked.
=> Add documentation on 5.6 support SLES 15.5

CHANGELOG.md, RELEASE.md, tools/autotag/templates/rocm_changes/5.6.0.md
=> Update release notes and changelog

docs/how_to/system_debugging.md, docs/understand/More-about-how-ROCm-uses-PCIe-Atomics.rst
closes https://github.com/RadeonOpenCompute/ROCm/issues/2241
=> Fix or remove broken links

docs/reference/ai_tools.md, docs/reference/all.md, docs/reference/compilers.md, docs/reference/computer_vision.md, docs/reference/gpu_libraries/c++_primitives.md, docs/reference/gpu_libraries/communication.md, docs/reference/gpu_libraries/fft.md, docs/reference/gpu_libraries/linear_algebra.md, docs/reference/gpu_libraries/rand.md, docs/reference/hip.md, docs/reference/management_tools.md, docs/reference/validation_tools.md, docs/sphinx/_toc.yml.in
links to docs, github, and changelogs for projects
=> Links for Reference pages

CHANGELOG.md, RELEASE.md, tools/autotag/templates/rocm_changes/5.4.0.md, tools/autotag/templates/rocm_changes/5.6.0.md
from docs/5.6.0 branch to develop
=> Changelog updates for 5.6.0

docs/conf.py
Sample on 5.5.1: https://rocm.docs.amd.com/_/downloads/en/docs-5.5.1/pdf/
Ref: https://www.sphinx-doc.org/en/master/usage/configuration.html
=> Add configurations for PDF output on Read the Docs

.github/workflows/linting.yml
=> Use linting from rocm-docs-core

docs/release/versions.md, docs/sphinx/_toc.yml.in
https://advanced-micro-devices-demo--2331.com.readthedocs.build/en/2331/release/versions.html
=> ROCm Version page

CONTRIBUTING.md, docs/about.md, docs/contribute/feedback.md
Fix typos and add links to rocm-docs-core user and developer guides in contributing section
=> Update contributing section

docs/deploy/linux/installer/install.md, docs/deploy/linux/os-native/install.md, docs/deploy/linux/os-native/upgrade.md
Resolves  #2373
Side note: we should look into templating/substitutions into code blocks to make this automated.
=> Update version in install guide to 5.6

docs/deploy/linux/installer/install.md
=> 	modified:   install.md

docs/deploy/linux/installer/install.md
=> Fix missing '--append' flag in install instructions

docs/how_to/tensorflow_install/tensorflow_install.md, tools/autotag/templates/rocm_changes/5.7.0.md
Should be merged/cherry-picked into https://github.com/RadeonOpenCompute/ROCm/pull/2374 and generate a new change log
=> Added notes for incompatibilities with certain TensorFlow versions.

docs/conceptual/using-gpu-sanitizer.md
rebase of https://github.com/RadeonOpenCompute/ROCm/pull/2461
=> Update Address Sanitizer Usage docs

docs/conceptual/using-gpu-sanitizer.md
=> Update Address Sanitizer docs (using-gpu-sanitizer.md)

default.xml
Update version to 5.7
Added a few new projects.
=> Update default.xml for 5.7

CHANGELOG.md, RELEASE.md, tools/autotag/templates/rocm_changes/5.7.0.md
=> Adjust 5.7.0 highlights

.wordlist.txt, docs/conceptual/gpu_memory.md, docs/conceptual/index.md
Closes https://github.com/RadeonOpenCompute/ROCm/issues/2265
=> GPU memory model

docs/release/windows_support.md
=> Fix incorrect LLVM target for RX 7600 in Windows Support page

docs/how-to/Spack.md
Format properly using tabs
See https://advanced-micro-devices-demo--2528.com.readthedocs.build/en/2528/how-to/Spack.html
=> Docs: Update Spack prerequisite instructions

docs/conf.py
Includes updates for PDF and left sidebar header
=> Update rtd conf.py for 5.7.1

CHANGELOG.md
Targets the roc-5.7.x branch for https://github.com/RadeonOpenCompute/ROCm/pull/2537
=> Regenerate release notes with AMDMIGraphX

CHANGELOG.md, CONTRIBUTING.md, README.md, docs/CHANGELOG.md, docs/conceptual/ai-pytorch-inception.md, docs/conf.py, docs/install/linux/install.md, tools/autotag/templates/rocm_changes/5.7.0.md
=> Fix warnings

docs/understand/using_gpu_sanitizer.md
Once this is merged, roc-5.7.x is to be merged into docs/5.7.0
=> Update LLVM ASan documentation

docs/release/gpu_os_support.md, docs/release/windows_support.md, docs/understand/using_gpu_sanitizer.md
Primarily for the ASan document (docs/understand/using_gpu_sanitizer.md)
=> Merge roc-5.7.x updates into docs/5.7.1 branch

.github/ISSUE_TEMPLATE/0_issue_report.yml, .github/ISSUE_TEMPLATE/1_feature_request.yml, .github/ISSUE_TEMPLATE/config.yml, docs/deploy/docker.md, docs/reference/openmp/openmp.md, docs/release/gpu_os_support.md, docs/release/windows_support.md, docs/understand/using_gpu_sanitizer.md
Includes:
- some typo fixes
- updates to ASan docs
=> Merge roc-5.7.x into docs/5.7.1

CHANGELOG.md, RELEASE.md, docs/conf.py, docs/sphinx/_toc.yml.in, tools/autotag/templates/rocm_changes/5.2.0.md, tools/autotag/templates/rocm_changes/5.7.0.md
In conf.py: CHANGELOG.md to the docs/about folder, same as RELEASE.md (docs/about/release-notes.md)
Goal: To make CHANGELOG.md, RELEASE.md, and x.x.x.md match in content
Flow: x.x.x.md (eg: 5.7.0.md) gets updated, CHANGELOG.md is generated from autotag, then cut and paste into RELEASE.md
=> Updates for consistency

docs/understand/using_gpu_sanitizer.md
duplicates https://github.com/RadeonOpenCompute/ROCm/pull/2606 with clean history
=> Add Roopa's changes to gpu sanitizer doc

.readthedocs.yaml
=> Update rtd yaml config

CHANGELOG.md, RELEASE.md
For HIP 6.0 and rocprofiler 2.0.0
=> Manual update to Release Notes

.github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/issue_report.yml
Hello, this PR is updating the issue template for ROCm public repositories to make it easier for users to submit the details for issues and bugs. Problems pertaining to documentation or non-bug related, users have the ability to open a blank issue template to submit their report. 
Thank you,
Community Support Team (ML SW SDK)
=> Adding updated issue template

docs/conceptual/cmake-packages.rst, docs/how-to/gpu-enabled-mpi.rst
Closes https://github.com/ROCm/ROCm/issues/2768
=> docs(gpu-enabled-mpi.rst): Fix links to 3rd party support matrices

default.xml
Add hipBLASLt repo in manifest.
=> Add hipBLASLt in manifest.

.github/workflows/issue_retrieval.yml
I am tasked with adding a GitHub action to process incoming GitHub issues. The AMD GitHub admin team asked me to try out one of their runners and to do this I need to load in a workflow file.
=> Abhimeda adding workflow file to create GitHub Action

docs/conceptual/gpu-memory.md
Corrected hipExtMallocWithFlags coherence errors
=> corrections for Issue #2753

docs/release/versions.md
Relates to https://github.com/ROCm/ROCm/issues/2823
=> docs(versions.md): Add 5.6.1 to versions list

CHANGELOG.md
Added link to ROCm on Radeon install page
=> Updated New ROCm meta package section

default.xml
=> Update default.xml to version 6.0.2

docs/conceptual/gpu-arch/mi300.md, docs/contribute/doc-structure.md
Yesterday, I missed a rebase error at the following PR:
https://github.com/ROCm/ROCm/pull/2779
This PR is fixing the rebase error.
=> Branch rebase fix

docs/how-to/gpu-enabled-mpi.rst
provide the precise parameters required to run Open MPI with libfabric and rocm support.
=> minor update to the gpu-mpi section

docs/reference/api-libraries.md, docs/what-is-rocm.rst
Add links to rocDecode in 'What is ROCm' and 'API libraries'.
=> Cherry-pick: add rocDecode

default.xml, tools/autotag/tag_script.py
- Adds rocDecode to default.xml
- Groups/alphabetize other projects
- Update tag to 6.1.0
=> Update manifest for ROCm 6.1.0

.azuredevops/README.md, .azuredevops/components/HIP.yml, .azuredevops/components/ROCR-Runtime.yml, .azuredevops/components/ROCT-Thunk-Interface.yml, .azuredevops/components/copyHIP.yml, .azuredevops/components/llvm-project.yml, .azuredevops/components/rocm-cmake.yml, .azuredevops/components/rocm-core.yml, .azuredevops/components/rocminfo.yml, .azuredevops/components/rocprofiler-register.yml, .azuredevops/templates/steps/artifact-download.yml, .azuredevops/templates/steps/artifact-prepare-package.yml, .azuredevops/templates/steps/artifact-upload.yml, .azuredevops/templates/steps/build-cmake.yml, .azuredevops/templates/steps/build-script.yml, .azuredevops/templates/steps/ccache.yml, .azuredevops/templates/steps/checkout.yml, .azuredevops/templates/steps/dependencies.yml, .azuredevops/templates/steps/preamble.yml, .azuredevops/templates/steps/test.yml, .azuredevops/variables-global.yml
A base set of yaml files to orchestrate the build and testing of ROCm compiler and runtime components in an Azure DevOps project.
=> Base set of Azure DevOps pipeline library source

default.xml
Remove OpenCL-ICD-Loader and add hip-tests.
=> update the default.xml for ROCm6.1

.azuredevops/components/HIP.yml, .azuredevops/components/ROCR-Runtime.yml, .azuredevops/components/copyHIP.yml, .azuredevops/components/hipBLASLt.yml, .azuredevops/components/hipSOLVER.yml, .azuredevops/components/hipSPARSELt.yml, .azuredevops/components/llvm-project.yml, .azuredevops/components/rocgdb.yml, .azuredevops/components/rocminfo.yml, .azuredevops/components/roctracer.yml, .azuredevops/tag-builds/hipSOLVER.yml, .azuredevops/tag-builds/hipSPARSELt.yml, .azuredevops/tag-builds/rocgdb.yml, .azuredevops/templates/steps/artifact-upload.yml, .azuredevops/templates/steps/build-autotools.yml
-rocgdb
-hipother via HIP build with targeted platform
-hipSOLVER
-hipSPARSELt
=> Tag build pipelines for four more ROCm repos

docs/compatibility/compatibility-matrix.rst, docs/compatibility/precision-support.rst, docs/conf.py, docs/index.md, docs/reference/gpu-arch-specs.rst, docs/reference/rocm-tools.md, docs/sphinx/_toc.yml.in, docs/sphinx/static/css/rocm_custom.css
* add compatibility matrix and custom css
* fix toc
* reorder some components in matrix, add missing tools to reference page
* Update docs/compatibility/compatibility-matrix.rst
---------
=> Add compatibility matrix (#3082)

docs/contribute/building.md
closes https://github.com/ROCm/ROCm/issues/3094
=> Add more explanation about doc requirements

docs/release/versions.md
=> Add 6.1.1 to version list

.wordlist.txt, docs/conceptual/compiler-topics.md, docs/conceptual/using-gpu-sanitizer.md, docs/index.md, docs/sphinx/_toc.yml.in
updated wordlist for ASAN and LSAN
added Using compiler features to index and TOC
Retitled Using AddressSanitizer
=> updates for SWDEV-459863

.wordlist.txt, docs/conceptual/compiler-topics.md, docs/conceptual/using-gpu-sanitizer.md, docs/index.md, docs/sphinx/_toc.yml.in
update wordlist for ASan and LSan
Create Using compiler features in the index and TOC
Update Using AddressSanitizer
=> cherry-pick Docs/6.1.1

CHANGELOG.md, RELEASE.md, tools/autotag/templates/rocm_changes/6.1.1.md
This PR adds more specific Ubuntu kernel versions to the release notes and changelog to minimize user confusion.
=> Update Ubuntu kernel versions in Release Notes and Changelog

.azuredevops/components/AMDMIGraphX.yml, .azuredevops/components/hipfort.yml, .azuredevops/components/rocSOLVER.yml, .azuredevops/components/rocWMMA.yml, .azuredevops/tag-builds/AMDMIGraphX.yml, .azuredevops/tag-builds/hipfort.yml, .azuredevops/tag-builds/rocSOLVER.yml, .azuredevops/tag-builds/rocWMMA.yml, .wordlist.txt, CHANGELOG.md, RELEASE.md, docs/conceptual/compiler-topics.md, docs/conceptual/using-gpu-sanitizer.md, docs/index.md, docs/sphinx/_toc.yml.in, tools/autotag/templates/rocm_changes/6.1.1.md
to include https://github.com/ROCm/ROCm/pull/3116
=> Merge develop into roc-6.1.x

.github/CODEOWNERS
using the example 
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners
=> Update CODEOWNERS syntax for .azuredevops directory

.azuredevops/components/AMDMIGraphX.yml
Log of successful build:
https://dev.azure.com/ROCm-CI/ROCm-CI/_build/results?buildId=1211&view=logs&j=b0b0eb5e-9de9-5eb1-7212-04e102eae4f9
=> Compiling dockerless AMDMIGraphX Azure DevOps pipeline

docs/reference/gpu-arch-specs.rst
* Re-add glossary to hardware specification table
* PR findings
* PR findings
PR findings
* Update docs/reference/gpu-arch-specs.rst
* Update docs/reference/gpu-arch-specs.rst
* Update docs/reference/gpu-arch-specs.rst
* Update docs/reference/gpu-arch-specs.rst
* PR findings
---------
=> docs/6.1.1: Re-add glossary to hardware specification table (#3073)

.azuredevops/components/composable_kernel.yml, .azuredevops/components/hipBLAS.yml, .azuredevops/components/llvm-project.yml, .azuredevops/components/rocBLAS.yml, .azuredevops/components/rocSOLVER.yml
- composable_kernel
- hipBLAS
- rocBLAS
- rocSOLVER
Cleaned up unused flags from llvm-project
=> Update External CI Interdependencies for more repos

.azuredevops/components/MIVisionX.yml
compile fix
```
WARNING: OpenCV Not Found -- amd_opencv module excluded
```
=> CI - Update MIVisionX.yml

CHANGELOG.md, RELEASE.md, tools/autotag/templates/rocm_changes/6.1.1.md
Fix link to rocm_smi_lib changelog
Update RELEASE.md
=> Add missed ROCm SMI changelog notes (#3168)

docs/what-is-rocm.rst
corrected link to HIPCC documentation
=> hipcc doc link

.readthedocs.yaml
These are causing RTD builds to time out
=> Disable pdf builds

.readthedocs.yaml
These are causing RTD builds to time out
=> Disable PDF on 6.1.1

.azuredevops/components/hipBLASLt.yml
Co-authored by Joseph Macaranas, Alex Xu, and Daniel Su
=> Removing docker from hipBLASLt

docs/how-to/fine-tuning-llms/index.rst, docs/how-to/fine-tuning-llms/llm-inference-frameworks.rst, docs/how-to/fine-tuning-llms/model-acceleration-libraries.rst, docs/how-to/fine-tuning-llms/model-quantization.rst, docs/how-to/fine-tuning-llms/multi-gpu-fine-tuning-and-inference.rst, docs/how-to/fine-tuning-llms/overview.rst, docs/how-to/fine-tuning-llms/single-gpu-fine-tuning-and-inference.rst, docs/index.md, docs/sphinx/_toc.yml.in
This PR
- Updates the main title to be more precise
- Improves readability in code blocks where there are helpful comments.
- Fixes minor typos.
in the fine-tuning guide
=> Update fine-tuning guide: title, improve readibility in code blocks, fix typos

docs/reference/api-libraries.md, docs/what-is-rocm.rst
=> Fix MIVisionX 6.1.2

docs/compatibility/compatibility-matrix.rst, docs/what-is-rocm.rst
* Update links in compat matrix and what-is-rocm
* Tensorflow -> TensorFlow
* Remove extra lines
* Revert "Remove extra lines"
This reverts commit 607c4323ac77fc120bcbcf3183cbf70cff12073a.
ROCm Debug Agent
=> docs/6.1.0: Update links in compat matrix and what-is-rocm (#3253)

docs/compatibility/compatibility-matrix.rst, docs/what-is-rocm.rst
* Update links in compat matrix and what-is-rocm
* Tensorflow -> TensorFlow
* Remove extra lines
* Revert "Remove extra lines"
This reverts commit 607c4323ac77fc120bcbcf3183cbf70cff12073a.
ROCm Debug Agent
=> docs/6.1.1: Update links in compat matrix and what-is-rocm (#3253)

.azuredevops/templates/steps/dependencies-other.yml
=> External CI: non-interactive apt upgrades

.azuredevops/components/rocr_debug_agent.yml
Successful build log: https://dev.azure.com/ROCm-CI/ROCm-CI/_build/results?buildId=1797&view=results
=> External CI: updated rocr_debug_agent dependencies

.azuredevops/components/MIOpen.yml
Successful build log: https://dev.azure.com/ROCm-CI/ROCm-CI/_build/results?buildId=1795&view=results
=> External CI: updated MIOpen dependencies

docs/conceptual/using-gpu-sanitizer.md
=> update ASan content

docs/compatibility/compatibility-matrix.rst
=> Port aomp fix

docs/compatibility/compatibility-matrix.rst
=> Remove AOMP from compatibility matrix (#3289)

docs/about/compatibility/openmp.md
* Added deleted sections to openmp.md and other improvements
* Update openmp.md
=> Update link to command-line argument reference (#3270)

docs/conceptual/using-gpu-sanitizer.md
=> cherry-pick ASan content

docs/conceptual/using-gpu-sanitizer.md
=> cherry pick PR #3284

CHANGELOG.md, tools/autotag/templates/rocm_changes/6.0.0.md
Change broken link text to standard text due to the removal of the linked folders
=> remove nvcc

docs/conf.py
6.1.1 release notes are incorrectly dated 1-31
=> Update GA date in 6.1.1 release notes

CHANGELOG.md, tools/autotag/templates/rocm_changes/6.0.0.md
* remove nvcc
* Update CHANGELOG to match 6.0.0 template
---------
=> remove nvcc (#3313)

LICENSE, docs/about/license.md
updated LICENSE to 2024
updated Component paths and licensing information
=> license information updated

LICENSE, docs/about/license.md
* license information updated
* Young's comments
* Sam's comment
=> license information updated (#3339)

docs/about/license.md
add ROCm-Core
add AMD SMI
restore paragraph on ROCm packages
=> added ROCm Core and AMD SMI

docs/about/license.md
* added ROCm Core and AMD SMI
* fix URLs
=> added ROCm Core and AMD SMI (#3348)

docs/conf.py
These pages no longer exist or were moved to install docs
=> Remove article info for moved or deleted pages

docs/how-to/llm-fine-tuning-optimization/llm-inference-frameworks.rst, docs/how-to/llm-fine-tuning-optimization/optimizing-triton-kernel.rst
Remove confusing information from **Fine-tuning LLMs and inference optimization**
=> Add fixes to vLLM install and triton kernel optimization

docs/how-to/llm-fine-tuning-optimization/llm-inference-frameworks.rst, docs/how-to/llm-fine-tuning-optimization/optimizing-triton-kernel.rst
* Add fixes to vLLM install and triton kernel optimization
* Update TGI how-to
remove extra step in TGI
=> Add fixes to vLLM install and triton kernel optimization (#3366)

docs/how-to/llm-fine-tuning-optimization/llm-inference-frameworks.rst, docs/how-to/llm-fine-tuning-optimization/optimizing-triton-kernel.rst
* Add fixes to vLLM install and triton kernel optimization
* Update TGI how-to
remove extra step in TGI
=> docs/6.1.0: Add fixes to vLLM install and triton kernel optimization (#3366)

docs/how-to/llm-fine-tuning-optimization/llm-inference-frameworks.rst, docs/how-to/llm-fine-tuning-optimization/optimizing-triton-kernel.rst
* Add fixes to vLLM install and triton kernel optimization
* Update TGI how-to
remove extra step in TGI
=> docs/6.1.1: Add fixes to vLLM install and triton kernel optimization (#3366)

.azuredevops/components/composable_kernel.yml
The flag should be INSTANCES_ONLY instead of INSTANCE_ONLY.
Also added libdrm-dev to suppress warnings
=> External CI: Fix a typo from composable_kernel pipeline

.azuredevops/components/ROCmValidationSuite.yml
- replace googletest with libgtest-dev
- Add environment variables ROCM_PATH and HIP_INC_DIR
- Add CXX_COMPILER cmake flag
Successful build log: https://dev.azure.com/ROCm-CI/ROCm-CI/_build/results?buildId=3007&view=logs&j=a9dd7315-711f-5623-6d52-e9ce616061c5
=> Update ROCmValidationSuite pipeline according to the latest change

docs/what-is-rocm.rst
* update CLR docs reference
* Apply suggestions from code review
---------
=> docs/6.1.1: update CLR docs reference (#3389)

docs/what-is-rocm.rst
* update CLR docs reference
* Apply suggestions from code review
---------
=> docs/6.1.0: update CLR docs reference (#3389)

tools/autotag/util/__init__.py, tools/autotag/util/custom_templates/hipfort.py, tools/autotag/util/custom_templates/hipify.py, tools/autotag/util/custom_templates/rvs.py
Closes https://github.com/ROCm/ROCm/issues/3409
Affects autotag for: hipfort, hipify, rvs
=> [Changelog/release notes] Fix and add custom templates for autotag script

docs/reference/rocm-tools.md, docs/what-is-rocm.rst
Removed TransferBench from tools.
=> Removed TransferBench from the tools list

docs/conf.py
Closes https://github.com/ROCm/ROCm/issues/3432
Jinja is rendered via rocm-docs-core (changelog.py)
No temp directory is generated
Also applies some black formatting to conf.py
=> Remove unused configurations in conf.py

.azuredevops/components/ROCmValidationSuite.yml
New dependencies introduced by https://github.com/ROCm/ROCmValidationSuite/pull/779
Successful build: https://dev.azure.com/ROCm-CI/ROCm-CI/_build/results?buildId=4105&view=results
=> External CI: add rocRAND and hipRAND to ROCmValidationSuite

docs/conf.py
Closes https://github.com/ROCm/ROCm/issues/3464
=> Set env var for canonical URL

docs/release/versions.md
Closes https://github.com/ROCm/ROCm/issues/3504
=> Update version list with 6.2.0 (#3505) (#3506)

docs/release/versions.md
https://github.com/ROCm/ROCm/pull/3510 should be merged first
=> Merge roc-6.2.x into docs/6.2.0

docs/how-to/rocm-for-ai/train-a-model.rst
Recipes folder has moved to quick start.
=> Fix link to meta-llama finetuning recipes

default.xml
cherry pick add rocPyDecode repo to ROCm6.2 manifest file (#3541) to roc-6.2.x
=> Cherry pick #3541 to roc-6.2.x

docs/compatibility/compatibility-matrix.rst, docs/conceptual/ai-pytorch-inception.md, docs/how-to/deep-learning-rocm.rst, docs/how-to/llm-fine-tuning-optimization/model-acceleration-libraries.rst, docs/how-to/llm-fine-tuning-optimization/multi-gpu-fine-tuning-and-inference.rst, docs/how-to/llm-fine-tuning-optimization/single-gpu-fine-tuning-and-inference.rst, docs/how-to/rocm-for-ai/install.rst, docs/how-to/system-optimization/mi300a.rst, docs/how-to/system-optimization/mi300x.rst, docs/how-to/system-optimization/w6000-v620.md
* update fw install links
* fix more intersphinx links
* fix more links
=> roc-6.2.x: Fix intersphinx links (#3546)

docs/compatibility/compatibility-matrix.rst, docs/conceptual/ai-pytorch-inception.md, docs/how-to/deep-learning-rocm.rst, docs/how-to/llm-fine-tuning-optimization/model-acceleration-libraries.rst, docs/how-to/llm-fine-tuning-optimization/multi-gpu-fine-tuning-and-inference.rst, docs/how-to/llm-fine-tuning-optimization/single-gpu-fine-tuning-and-inference.rst, docs/how-to/rocm-for-ai/install.rst, docs/how-to/system-optimization/mi300a.rst, docs/how-to/system-optimization/mi300x.rst, docs/how-to/system-optimization/w6000-v620.md
* update fw install links
* fix more intersphinx links
* fix more links
=> docs/6.2.0: Fix intersphinx links (#3546)

docs/contribute/feedback.md
Rewrote the section to be minimalist and not specify the number of ways to provide feedback. Also removed the PR info since that's covered in Contributing.
=> Updated the Feedback section

.azuredevops/components/MIOpen.yml, .azuredevops/components/hipBLASLt.yml
https://dev.azure.com/ROCm-CI/ROCm-CI/_build/results?buildId=5780&view=results
=> External CI: add hipBLAS-common to MIOpen

.azuredevops/components/rocPyDecode.yml, .azuredevops/tag-builds/rocPyDecode.yml
Passing build log: https://dev.azure.com/ROCm-CI/ROCm-CI/_build/results?buildId=5957&view=results
=> External CI: Support for rocPyDecode

.azuredevops/components/HIP.yml, .azuredevops/components/hip-tests.yml, .azuredevops/tag-builds/hip-tests.yml, .azuredevops/templates/steps/build-cmake.yml
Passing build log: https://dev.azure.com/ROCm-CI/ROCm-CI/_build/results?buildId=5981&view=results
=> External: Build Pipeline for hip-tests

.azuredevops/templates/steps/artifact-download.yml
Fixes: https://github.com/ROCm/MIVisionX/pull/1416
=> External CI: change ROCR and rpp default branches

docs/how-to/system-optimization/mi300a.rst
This incorporates a change to the thread affinity section. More changes still to be added.
=> Expand the section on changing thread affinity

.wordlist.txt, docs/how-to/llm-fine-tuning-optimization/model-acceleration-libraries.rst
* Add FBGEMM/FBGEMM_GPU to the Model acceleration libraries page
* Add words to wordlist and fix a typo
* Add new sections for Docker and testing
* Incorporate comments from the external review
* Some minor edits and clarifications
* Incorporate further review coments and fix test section
* Add comment to test section
* Change git clone command for FBGEMM repo
* Change Docker command
* Changes from internal review
* Fix linting issue
=> Cherry-pick to "roc-6.2.x": Add FBGEMM/FBGEMM_GPU to the Model acceleration libraries page (#3659)

default.xml
rocm-examples is the replacement.
=> Remove HIP-Examples from default.xml

.azuredevops/components/HIPIFY.yml, .azuredevops/templates/steps/artifact-download.yml
40% pass rate for this initial change. Would like to push this through to at least change the build process and then defer fixing the remaining test failures.
Build Log: https://dev.azure.com/rocm-ci/ROCm-CI/_build/results?buildId=7606&view=results
=> External CI: Change HIPIFY pipelines to include testing

.azuredevops/components/rccl.yml, .azuredevops/templates/steps/dependencies-cmake-latest.yml
Adds latest cmake and libnuma-dev
Build log: https://dev.azure.com/ROCm-CI/ROCm-CI/_build/results?buildId=7604&view=results
=> External CI: rccl use latest cmake

RELEASE.md
=> cherry pick broken release notes link fix

docs/how-to/llm-fine-tuning-optimization/model-quantization.rst
=> Docs/6.2.0: add missing make command to bitsandbytes install commands (#3722)

docs/how-to/llm-fine-tuning-optimization/model-quantization.rst
=> Add docs fixes to roc-6.2.x

.azuredevops/components/hipfort.yml
Referred to public documentation, build instructions, and iterative debug runs to update build flags, publish new artifacts, and run tests. Test results are not parsed and graphed in Azure.
[Passing build log](https://dev.azure.com/rocm-ci/ROCm-CI/_build/results?buildId=8062&view=results)
=> External CI: hipfort smoke tests

.azuredevops/components/hip-tests.yml
Test failures are known issues and have internal tickets assigned to them.
Test log:
https://dev.azure.com/ROCm-CI/ROCm-CI/_build/results?buildId=7834&view=logs&j=788b2155-293d-5df9-e82c-92ef9f7bf1de&t=e9e58695-78a9-5196-b586-1c2dbf1d1f3c
=> External CI: hip-tests unit tests

RELEASE.md
* fix wording in RCCL known issue
=> Cherry pick to 6.2 release branch: Update RCCL known issue wording (#3775)

.azuredevops/components/rocPyDecode.yml
[Passing Log](https://dev.azure.com/rocm-ci/ROCm-CI/_build/results?buildId=8514&view=results)
=> External CI: rocPyDecode Smoke Test

.azuredevops/components/omniperf.yml, .azuredevops/tag-builds/omniperf.yml, .azuredevops/templates/steps/dependencies-other.yml
- Referred to public documentation, source, and iterative attempts to create and improve build and test pipeline.
- ctest failures are due to the test node not having expected marketing name string and override not working.
- The fix should be on the omniperf repo side of things, so this pull request should be fine as is.
[Pipeline Log](https://dev.azure.com/rocm-ci/ROCm-CI/_build/results?buildId=8530&view=results)
=> External CI: omniperf pipeline

docs/compatibility/compatibility-matrix-historical-6.0.csv, docs/compatibility/compatibility-matrix.rst
Need to fix Footnote typo.  The 3rd column is 6 1.0.
=> fix footnote for 6.1.0

RELEASE.md, docs/compatibility/compatibility-matrix-historical-6.0.csv, docs/compatibility/compatibility-matrix.rst, tools/autotag/templates/support/6.2.1.md
* add ubuntu 24.04.1
* add 24.04.1 to bottom os section
* fix heading and template
* Update compatibility-matrix.rst for OpenMP version
* Update compatibility-matrix-historical-6.0.csv for OpenMP version
* rm ubuntu 24.04.1 from 6.2.0
* Update docs/compatibility/compatibility-matrix.rst
* rm duplicate ubuntu in historical
---------
=> roc-6.2.x: Add Ubuntu 24.04.1 (#3801)

RELEASE.md, docs/compatibility/compatibility-matrix-historical-6.0.csv, docs/compatibility/compatibility-matrix.rst, tools/autotag/templates/support/6.2.1.md
* add ubuntu 24.04.1
* add 24.04.1 to bottom os section
* fix heading and template
* Update compatibility-matrix.rst for OpenMP version
* Update compatibility-matrix-historical-6.0.csv for OpenMP version
* rm ubuntu 24.04.1 from 6.2.0
* Update docs/compatibility/compatibility-matrix.rst
* rm duplicate ubuntu in historical
---------
=> Docs/6.2.2: Add Ubuntu 24.04.1 (#3801)

docs/about/license.md
remove statement about llvm-alt proprietary license
=> remove llvm-alt license

.azuredevops/components/omnitrace.yml, .azuredevops/tag-builds/omnitrace.yml
Collaborative effort with @danielsu-amd to get build working in Azure VM.
Next step is to add testing on gfx942.
[Passing Build Log](https://dev.azure.com/ROCm-CI/ROCm-CI/_build/results?buildId=8917&view=results)
=> External CI: omnitrace build pipeline

README.md
CHANGELOG.md doesn't exist anymore
=> Point to release history instead of changelog

docs/compatibility/compatibility-matrix.rst
* updated the radeon note, as it were
* updated the note again
=> updated the radeon note, as it were (#3857)

.wordlist.txt, docs/conceptual/oversubscription.rst, docs/index.md, docs/sphinx/_toc.yml.in
(cherry picked from commit d0ecf51b0c9202475e2abe90a45b50df0de6d7ae)
=> docs/6.2.4: add oversubscription conceptual doc (#3885)

.wordlist.txt, docs/conceptual/oversubscription.rst, docs/index.md, docs/sphinx/_toc.yml.in
(cherry picked from commit d0ecf51b0c9202475e2abe90a45b50df0de6d7ae)
=> docs/6.2.2: add oversubscription conceptual doc (#3885)

docs/how-to/llm-fine-tuning-optimization/model-quantization.rst, docs/how-to/llm-fine-tuning-optimization/single-gpu-fine-tuning-and-inference.rst
(cherry picked from commit b541be7bcb6541b4a00633972ed5d0a546ad4e85)
=> [docs/6.2.2] Update bitsandbytes branch in docs (#3898)

docs/how-to/llm-fine-tuning-optimization/model-quantization.rst, docs/how-to/llm-fine-tuning-optimization/single-gpu-fine-tuning-and-inference.rst
(cherry picked from commit b541be7bcb6541b4a00633972ed5d0a546ad4e85)
=> Update bitsandbytes branch in docs (#3898)

.azuredevops/nightly/pytorch.yml
- Change is only for nightly pytorch job
=> External CI: Change when snap installs cmake on test system

docs/reference/gpu-arch-specs.rst
* added a link to the compatibility matrix
* removed quotes
=> added a link to the compatibility matrix (#3904)

.azuredevops/components/AMDMIGraphX.yml
https://dev.azure.com/ROCm-CI/ROCm-CI/_build/results?buildId=10698&view=results
=> External CI: AMDMIGraphX greater-equal pip dependencies

.wordlist.txt, docs/conf.py, docs/how-to/performance-validation/mi300x/vllm-benchmark.rst, docs/how-to/tuning-guides/mi300x/index.rst, docs/index.md, docs/sphinx/_toc.yml.in
(cherry picked from commit 35b16c1293d1260d567d7c76f5b2d9e8086b787c)
=> add vllm performance validation doc (#3964)

.wordlist.txt, docs/how-to/llm-fine-tuning-optimization/llm-inference-frameworks.rst, docs/how-to/rocm-for-ai/deploy-your-model.rst, docs/how-to/tuning-guides/mi300x/workload.rst
(cherry picked from commit 0fe08d93d708fc1a19d5020c9f65669b692b15e7)
=> Update links to vllm perf validation doc (#3971)

docs/index.md
Co-authored-by: prbasyal <prbasyal@amd.com>
(cherry picked from commit 59eb02af42f7cc319f5e74ad51780637d4a9e6eb)
=> Changed the introductory text linked to Radeon (#3988)

docs/reference/gpu-arch-specs.rst
* Improve consistency of the gpu-arch-specs table.
* Add XCD to the glossary.
(cherry picked from commit d367700f849d52267c0b8c3af6b2651f09b338e5)
=> Improve consistency of the gpu-arch-specs table. (#3936)

docs/release/versions.md
=> Remove extra line from version list

docs/index.md, docs/sphinx/_toc.yml.in
Change TOC and index reference titles in How to category
=> Change How to ToC and index

docs/reference/api-libraries.md, docs/what-is-rocm.rst
(cherry picked from commit 5e6ddec3858b9797aeb06587c1ef0e4b441e9cb9)
=> Update what-is-rocm.rst (#4122)

RELEASE.md
=> Revert "Update RELEASE.md"

docs/index.md
Remove Programming Guide topic from "How to"
=> Update index.md (#4144)

RELEASE.md
* Added MIGraphX changes
* removed gfx support
* Update RELEASE.md
Co-authored-by: Jeffrey Novotny <jnovotny@amd.com>
* Update RELEASE.md
Co-authored-by: Jeffrey Novotny <jnovotny@amd.com>
* Update RELEASE.md
Co-authored-by: Jeffrey Novotny <jnovotny@amd.com>
* Update RELEASE.md
Co-authored-by: Jeffrey Novotny <jnovotny@amd.com>
* Update RELEASE.md
* Update RELEASE.md
Co-authored-by: Jeffrey Novotny <jnovotny@amd.com>
* Update RELEASE.md
Co-authored-by: Jeffrey Novotny <jnovotny@amd.com>
* Update RELEASE.md
Co-authored-by: Jeffrey Novotny <jnovotny@amd.com>
* Update RELEASE.md
Co-authored-by: Jeffrey Novotny <jnovotny@amd.com>
* Update RELEASE.md
* Update RELEASE.md
Co-authored-by: Jeffrey Novotny <jnovotny@amd.com>
---------
Co-authored-by: Jeffrey Novotny <jnovotny@amd.com>
(cherry …
=> Cherry pick release note update

RELEASE.md
Remove upcoming changes section in HIP changes
=> Remove upcoming changes section in HIP changes

.azuredevops/components/HIP.yml, .azuredevops/components/MIVisionX.yml, .azuredevops/components/ROCR-Runtime.yml, .azuredevops/components/ROCdbgapi.yml, .azuredevops/components/ROCmValidationSuite.yml, .azuredevops/components/amdsmi.yml, .azuredevops/components/hipRAND.yml, .azuredevops/components/hipSOLVER.yml, .azuredevops/components/hipSPARSE.yml, .azuredevops/components/rocALUTION.yml, .azuredevops/components/rocDecode.yml, .azuredevops/components/rocJPEG.yml, .azuredevops/components/rocRAND.yml, .azuredevops/components/rocm-cmake.yml, .azuredevops/components/rocm-core.yml, .azuredevops/components/rocm_smi_lib.yml, .azuredevops/components/rocminfo.yml, .azuredevops/components/rocprofiler-register.yml, .azuredevops/components/rocr_debug_agent.yml, .azuredevops/components/roctracer.yml, .azuredevops/components/rpp.yml
- pip might not be installed on LOW_BUILD_POOL VMs.
- Ensure it is installed to not fail the 'pip list' step.
=> External CI: Install pip on LOW_BUILD_POOL pipelines

.azuredevops/components/ROCR-Runtime.yml, .azuredevops/components/amdsmi.yml, .azuredevops/components/rocprofiler-sdk.yml, .azuredevops/components/rpp.yml, .azuredevops/nightly/pytorch.yml
- pip update click module for test failures.
- [Test results are at 99.8% with these fixes.](https://dev.azure.com/ROCm-CI/ROCm-CI/_build/results?buildId=19329&view=ms.vss-test-web.build-test-results-tab)
=> External CI: Remove aotriton from pytorch build

.azuredevops/templates/steps/docker-container.yml
- The URL is being repeated in the container URL due to parameter.
- Add the build ID to the URL being printed out.
=> External CI: Docker URL Update

.azuredevops/components/rccl.yml, .azuredevops/components/rocDecode.yml, .azuredevops/components/rocJPEG.yml
- rccl
- Adds roctracer as a dependency: https://github.com/ROCm/rccl/pull/1506
- Sorted component list
- https://dev.azure.com/ROCm-CI/ROCm-CI/_build/results?buildId=19679&view=results
- rocDecode
- Removed unused and undefined `JOB_GPU_TARGET` var
- rocJPEG
- Added `JOB_GPU_TARGET` var
- Set `registerROCmPackages` to true for docker creation
- https://dev.azure.com/ROCm-CI/ROCm-CI/_build/results?buildId=19678&view=results
=> Ex CI: rccl, rocDecode, rocJPEG fixes

.azuredevops/templates/steps/docker-container.yml
- Add DEBIAN_FRONTEND=noninteractive to apt install calls in the Dockerfile creation.
- Make parameter order consistent with these apt calls.
=> External CI: Docker Environment Creation Apt Fix

docs/reference/precision-support.rst
Already got approval from @lpaoletti. Could I get a codeowner approval?
=> Precision support page update

.wordlist.txt, docs/about/license.md, docs/how-to/rocm-for-ai/inference/vllm-benchmark.rst
(cherry picked from commit https://github.com/ROCm/ROCm/commit/9b0ae86b1bd1f7872e318b08ca4d3c091e6f84c8)
(cherry picked from commit https://github.com/ROCm/ROCm/commit/2751a17cf05f9c68e19d39444208ba41c131106b)
=> [docs/6.3.1] Update vLLM benchmarking guide

.wordlist.txt, docs/about/license.md, docs/how-to/rocm-for-ai/inference/vllm-benchmark.rst
(cherry picked from commit https://github.com/ROCm/ROCm/commit/9b0ae86b1bd1f7872e318b08ca4d3c091e6f84c8)
(cherry picked from commit https://github.com/ROCm/ROCm/commit/2751a17cf05f9c68e19d39444208ba41c131106b)
=> [docs/6.3.2] Update vLLM benchmarking guide

docs/reference/gpu-arch-specs.rst
Adds 2 columns for "Device Major version" and "Device Minor version"
=> Docs: Add Device Major/Minor Versions to gpu-arch-spec.rst

RELEASE.md
=> wavesize Release Note update

RELEASE.md
=> Revert "wavesize Release Note update"

docs/how-to/rocm-for-ai/training/benchmark-docker/megatron-lm.rst
(cherry picked from commit 1ea1c5c6e08291ec527c3bc37ee83a6287ef774b)
=> [docs/6.3.3] fix tab sync and nested tab Megatron-LM doc (#4409)

.wordlist.txt, docs/reference/gpu-arch-specs.rst
Update the description and column positioning of the major and minor version
=> Docs: Fix gpu-arch-spec.rst

.gitignore, docs/compatibility/ml-compatibility/jax-compatibility.rst, docs/compatibility/ml-compatibility/pytorch-compatibility.rst, docs/compatibility/ml-compatibility/tensorflow-compatibility.rst, docs/conf.py, docs/extension/version-ref.py
(cherry picked from commit https://github.com/ROCm/ROCm/commit/cd85ccd539f9217b8d34269f377916d2908907db)
(cherry picked from commit https://github.com/ROCm/ROCm/commit/fa0e21290638646a39cdc43ef46fb4bb6c4d4c65)
=> Add docs fixes to 6.3.3

.azuredevops/templates/steps/dependencies-other.yml
- Also add fix-missing parameter to apt install
=> External CI: Add default ubuntu repos to sources.list

.wordlist.txt, docs/how-to/rocm-for-ai/inference/index.rst, docs/how-to/rocm-for-ai/training/benchmark-docker/megatron-lm.rst, docs/how-to/rocm-for-ai/training/benchmark-docker/pytorch-training.rst
(cherry picked from commit 2fca094531826c0b9a720a1515422ae51841f223)
=> PyTorch training Docker update 25.4 (#4482)

RELEASE.md, docs/compatibility/compatibility-matrix.rst
=> Revert "rocAL added to ROCm 6.1.5"
